"use strict";
/* German UI dictionary, translated from the Japanese master (UIT.ja in index.html);
   key set mirrors UIT.en exactly - only the wording differs.
   Function values (zCount / newEnd / dupEnd) stay functions.
   Style: simple picture-book German. Ending names match ZK_DE in www\story_*_de.js. */

var UIT_DE = {
  title:'Werde die Hauptfigur der Märchen!',
  subtitle:'Die Geschichte ändert sich mit jeder Wahl',
  start:'Starten', cont:'Weiterlesen', zukan:'Sammlung der Enden', settings:'⚙️ Einstellungen',
  footVer:'v1.8.3',
  footOrig:'Alle Texte und Bilder sind Originale.',
  footFirst:'Dein erster Durchgang folgt der ursprünglichen Geschichte.',
  footCreate:'Die verzweigten Geschichten und Enden sind Originale nur für diese App.',
  credit:'App von SOYOGI, Beratungsstelle für Pflege und Unterstützung (Beratung nur auf Japanisch)',
  privacy:'Datenschutzerklärung',
  reset:'Alle Aufzeichnungen löschen und neu beginnen',
  resetConfirm:'Wirklich löschen? (Noch einmal drücken zum Löschen)',
  selTitle:'Welche Geschichte liest du?',
  momoName:'Momotaro, der Pfirsichjunge',
  momoTagFirst:'Dein erster Durchgang folgt der ursprünglichen Geschichte',
  momoTag:'Ein japanisches Märchen voller Abenteuer · 8 Enden',
  oniName:'Die Geschichte des Ogers', oniTag:'Momotaro mit den Augen eines Ogers · 5 Enden',
  oniLock:'Beende Momotaro einmal, um sie freizuschalten',
  kijiName:'Die Geschichte des Fasans', kijiTag:'Die Geschichte des kleinsten Gefährten · 2 Enden',
  kijiLock:'Beende Momotaro zusammen mit dem Fasan, um sie freizuschalten',
  akzName:'Rotkäppchen',
  akzTagFirst:'Dein erster Durchgang folgt der ursprünglichen Geschichte',
  akzTag:'Ein Grimm-Märchen voller Spannung · 6 Enden',
  wolfName:'Die Geschichte des Wolfes', wolfTag:'Die Geschichte mit den Augen des Wolfes · 3 Enden',
  wolfLock:'Beende Rotkäppchen einmal, um sie freizuschalten',
  gmaName:'Die Geschichte der Großmutter', gmaTag:'Sie ist nicht nur da, um gerettet zu werden · 2 Enden',
  gmaLock:'Finde das Ende „Die Klugheit der Großmutter“, um sie freizuschalten',
  kabuName:'Die große Rübe',
  kabuTagFirst:'Dein erster Durchgang folgt der ursprünglichen Geschichte',
  kabuTag:'Ein russisches Märchen vom Zusammenhalten · 4 Enden',
  turnipName:'Die Geschichte der Rübe', turnipTag:'Auch wer gezogen wird, hat Gefühle · 2 Enden',
  turnipLock:'Beende Die große Rübe einmal, um sie freizuschalten',
  mouseName:'Die Geschichte der Maus', mouseTag:'Die Kleinste gibt den letzten Schub · 2 Enden',
  mouseLock:'Finde ein Ende in der Geschichte der Rübe, um sie freizuschalten',
  uraName:'Urashima Taro',
  uraTagFirst:'Dein erster Durchgang folgt der ursprünglichen Geschichte',
  uraTag:'Ein japanisches Märchen voller Wehmut · 5 Enden',
  kameName:'Die Geschichte der Schildkröte', kameTag:'Der beste Platz ist auf meinem Rücken · 2 Enden',
  kameLock:'Beende Urashima Taro einmal, um sie freizuschalten',
  himeName:'Die Geschichte von Prinzessin Otohime', himeTag:'Der Wunsch, im Tamatebako verschlossen · 2 Enden',
  himeLock:'Finde das Ende „Taro als Kranich“ oder „Das ungeöffnete Tamatebako“, um sie freizuschalten',
  butaName:'Die drei kleinen Schweinchen',
  butaTagFirst:'Dein erster Durchgang folgt der ursprünglichen Geschichte',
  butaTag:'Ein englisches Märchen vom Pusten und Standhalten · 4 Enden',
  pwolfName:'Die Geschichte des hungrigen Wolfes', pwolfTag:'Hungrig, und immer der Überlistete · 2 Enden',
  pwolfLock:'Beende Die drei kleinen Schweinchen einmal, um sie freizuschalten',
  prengaName:'Die Geschichte des Ziegelhauses', prengaTag:'Auch wer beschützt, hat seinen Stolz · 2 Enden',
  prengaLock:'Finde das Ende „Die echte englische Geschichte“ oder „Von Anfang an zu dritt“, um sie freizuschalten',
  hgName:'Hänsel und Gretel',
  hgTagFirst:'Dein erster Durchgang folgt der ursprünglichen Geschichte',
  hgTag:'Ein Grimm-Märchen vom Haus aus Süßigkeiten · 4 Enden',
  majoName:'Die Geschichte der Hexe', majoTag:'All die Jahre allein Süßigkeiten backen · 2 Enden',
  majoLock:'Beende Hänsel und Gretel einmal, um sie freizuschalten',
  toriName:'Die Geschichte des weißen Vogels', toriTag:'Die Brotkrumen habe ich gefressen · 2 Enden',
  toriLock:'Finde das Ende „Ans andere Ufer“ oder „Der Winter des Dorfes“, um sie freizuschalten',
  kgName:'Prinzessin Kaguya',
  kgTagFirst:'Dein erster Durchgang folgt der ursprünglichen Geschichte',
  kgTag:'Ein japanisches Märchen von der Prinzessin, die zum Mond zurückkehrt · 4 Enden',
  okinaName:'Die Geschichte vom alten Paar', okinaTag:'Die Tage danach, für die beiden Zurückgebliebenen · 2 Enden',
  okinaLock:'Beende Prinzessin Kaguya einmal, um sie freizuschalten',
  tsukiName:'Die Geschichte des Mondboten', tsukiTag:'Aus einem Land, das keine Tränen kennt · 2 Enden',
  tsukiLock:'Finde das Ende „Vor dem Federgewand“ oder „Das Lebenselixier“, um sie freizuschalten',
  brName:'Die Bremer Stadtmusikanten',
  brTagFirst:'Dein erster Durchgang folgt der ursprünglichen Geschichte',
  brTag:'Ein Grimm-Märchen von 4 Stimmen im Chor · 4 Enden',
  dorobouName:'Die Geschichte der Räuber', dorobouTag:'Der Räuber, der ins dunkle Haus zurückging · 2 Enden',
  dorobouLock:'Beende Die Bremer Stadtmusikanten einmal, um sie freizuschalten',
  ondoriName:'Die Geschichte des Hahns', ondoriTag:'Die Stimme, die zu Suppe werden sollte · 2 Enden',
  ondoriLock:'Finde das Ende „In der Stadt Bremen“ oder „Morgen im Wald“, um sie freizuschalten',
  juName:'Wie die zwölf Tiere gewählt wurden',
  juTagFirst:'Dein erster Durchgang folgt der ursprünglichen Geschichte',
  juTag:'Ein japanisches Märchen davon, wie die Jahre ihre Namen bekamen · 4 Enden',
  jnekoName:'Die Geschichte der Katze', jnekoTag:'Die Katze, die den Tag falsch gehört hat · 2 Enden',
  jnekoLock:'Beende Wie die zwölf Tiere gewählt wurden einmal, um sie freizuschalten',
  jnezumiName:'Die Geschichte der Ratte', jnezumiTag:'Die Ratte, die den wahren Tag nicht nannte · 2 Enden',
  jnezumiLock:'Finde das Ende „Auf dem Rücken des Ochsen“ oder „Der Gruß in jedem Jahr“, um sie freizuschalten',
  tsName:'Der Kranich, der die Freundlichkeit erwiderte',
  tsTagFirst:'Dein erster Durchgang folgt der ursprünglichen Geschichte',
  tsTag:'Ein japanisches Märchen vom Kranich an einem Schneetag · 4 Enden',
  tsuruName:'Die Geschichte des Kranichs', tsuruTag:'Der Kranich, der beim Weben die Federn zählt · 2 Enden',
  tsuruLock:'Beende „Der Kranich, der die Freundlichkeit erwiderte“ einmal, um sie freizuschalten',
  /* 🔴あかずきんの Die Geschichte der Großmutter と まぎれない ように Winter を 入れる */
  tbaaName:'Der Winter der alten Frau', tbaaTag:'Ihr wurde gesagt, sie solle nicht hinsehen · 2 Enden',
  tbaaLock:'Finde das Ende „Du musst nicht mehr weben“ oder „Ein Winter ohne Blick“, um sie freizuschalten',
  /* 🔴"Alibaba" と つづけて 書かない(分かち書きの "Ali Baba" だけ) */
  abName:'Ali Baba und die 40 Räuber',
  abTagFirst:'Dein erster Durchgang folgt der ursprünglichen Geschichte',
  abTag:'Ein persisches Märchen von der Felsentür · 4 Enden',
  moruName:'Morgianas Geschichte', moruTag:'Die Dienerin, der nichts entgeht · 2 Enden',
  moruLock:'Beende Ali Baba und die 40 Räuber einmal, um sie freizuschalten',
  /* 🔴ブレーメンの Die Geschichte der Räuber と まぎれない ように Anführer と 書く */
  kashiraName:'Die Geschichte des Anführers',
  kashiraTag:'Der Anführer, dessen Geheimnis entdeckt wurde · 2 Enden',
  kashiraLock:'Finde das Ende „Seile und die Stadtwache“ oder „Der Anführer floh“, um sie freizuschalten',
  kzName:'Der Nordwind und die Sonne',
  kzTagFirst:'Dein erster Durchgang folgt der ursprünglichen Geschichte',
  kzTag:'Eine Fabel von Äsop vom Wettstreit um einen Mantel · 4 Enden',
  kitakazeName:'Die Geschichte vom Nordwind', kitakazeTag:'Kräftig blasen ist die Arbeit des Nordwinds · 2 Enden',
  kitakazeLock:'Beende Der Nordwind und die Sonne einmal, um sie freizuschalten',
  taiyouName:'Die Geschichte von der Sonne', taiyouTag:'Scheinen ist die Arbeit der Sonne · 2 Enden',
  taiyouLock:'Finde das Ende „Waschwetter zu zweit“ oder „Eine Rast im Schatten“, um sie freizuschalten',
  prep:'In Vorbereitung',
  titleBack:'Zurück zum Titel', selBack:'Zurück zur Auswahl', next:'Weiter ▼', back:'Zurück',
  zTitle:'Sammlung der Enden',
  zCount:(n,t)=>'Gefundene Enden: '+n+' / '+t,
  zNote:'* Bis auf das ursprüngliche Ende sind alle Enden Originale nur für diese App.',
  zFound:'▶ Zum Nachlesen tippen', zHint:'Hinweis: ', unknown:'? ? ?',
  newEnd:n=>'★ Neues Ende „'+n+'“ zur Sammlung hinzugefügt!',
  dupEnd:n=>'(Das Ende „'+n+'“ ist schon in deiner Sammlung)',
  unlockChoice:'★ Ab jetzt kannst du deinen eigenen Weg wählen!',
  unlockNote:'(Die verzweigten Geschichten sind Originale nur für diese App)',
  unlockOni:'★ „Die Geschichte des Ogers“ ist jetzt freigeschaltet!',
  unlockKiji:'★ „Die Geschichte des Fasans“ ist jetzt freigeschaltet!',
  unlockWolf:'★ „Die Geschichte des Wolfes“ ist jetzt freigeschaltet!',
  unlockGma:'★ „Die Geschichte der Großmutter“ ist jetzt freigeschaltet!',
  unlockTurnip:'★ „Die Geschichte der Rübe“ ist jetzt freigeschaltet!',
  unlockMouse:'★ „Die Geschichte der Maus“ ist jetzt freigeschaltet!',
  unlockKame:'★ „Die Geschichte der Schildkröte“ ist jetzt freigeschaltet!',
  unlockHime:'★ „Die Geschichte von Prinzessin Otohime“ ist jetzt freigeschaltet!',
  unlockPwolf:'★ „Die Geschichte des hungrigen Wolfes“ ist jetzt freigeschaltet!',
  unlockPrenga:'★ „Die Geschichte des Ziegelhauses“ ist jetzt freigeschaltet!',
  unlockMajo:'★ „Die Geschichte der Hexe“ ist jetzt freigeschaltet!',
  unlockTori:'★ „Die Geschichte des weißen Vogels“ ist jetzt freigeschaltet!',
  unlockOkina:'★ „Die Geschichte vom alten Paar“ ist jetzt freigeschaltet!',
  unlockTsuki:'★ „Die Geschichte des Mondboten“ ist jetzt freigeschaltet!',
  unlockDorobou:'★ „Die Geschichte der Räuber“ ist jetzt freigeschaltet!',
  unlockOndori:'★ „Die Geschichte des Hahns“ ist jetzt freigeschaltet!',
  unlockJneko:'★ „Die Geschichte der Katze“ ist jetzt freigeschaltet!',
  unlockJnezumi:'★ „Die Geschichte der Ratte“ ist jetzt freigeschaltet!',
  unlockTsuru:'★ „Die Geschichte des Kranichs“ ist jetzt freigeschaltet!',
  unlockTbaa:'★ „Der Winter der alten Frau“ ist jetzt freigeschaltet!',
  unlockMoru:'★ „Morgianas Geschichte“ ist jetzt freigeschaltet!',
  unlockKashira:'★ „Die Geschichte des Anführers“ ist jetzt freigeschaltet!',
  unlockKitakaze:'★ „Die Geschichte vom Nordwind“ ist jetzt freigeschaltet!',
  unlockTaiyou:'★ „Die Geschichte von der Sonne“ ist jetzt freigeschaltet!',
  btnZukan:'Die Sammlung der Enden ansehen', btnAgain:'Diese Geschichte noch einmal lesen',
  btnSelect:'Zurück zur Auswahl', btnZBack:'Zurück zur Sammlung',
  setTitle:'Einstellungen', lblFs:'Schriftgröße', lblBgm:'Musik', lblSe:'Klangeffekte', lblLang:'Sprache / Language',
  fsOpts:['Klein','Normal','Groß'], volOpts:['Aus','Leise','Normal','Laut'],
  yes:'Ja', no:'Nein', quitConfirm:'Zurück zur Auswahl? („Weiterlesen“ verschwindet dann)',
  seal:['Ende'],
  /* はじめての あそびかた(2026-09-30)。{start} などは いまの ことばの ボタンの 文字に おきかわる(index.html guideText) */
  guideTitle:'So wird gespielt', guideStep:'{n} / {m}', guidePrev:'Zurück', guideNext:'Weiter', guideStart:'Spielen', guideAgain:'Noch einmal ansehen',
  guideHeads:[
    'Deine Wahl verändert die Geschichte',
    'So fängst du an',
    'Lesen und wählen',
    'Mittendrin aufhören',
    '{zukan}',
    'Deine Aufzeichnungen bleiben auf diesem Gerät',
    'Einstellungen und Sprache'
  ],
  guideBodies:[
    'In diesem Spiel liest du Märchen aus aller Welt. Es gibt 12 Geschichten, zum Beispiel „{momoName}“ und „{akzName}“.\nWenn du unterwegs selbst wählst, ändert sich das Ende.\nEgal, was du wählst: Verlieren kannst du nie.',
    'Tippe auf dem Titelbildschirm auf „{start}“ und wähle eine Geschichte.\nBeim ersten Mal folgt jede Geschichte dem ursprünglichen Märchen.\nAb dem zweiten Mal gibt es Stellen, an denen du selbst wählst.',
    'Tippe auf den Bildschirm oder auf „{next}“, um weiterzugehen.\nWo es eine Wahl gibt, tippst du auf die Schaltfläche, die dir gefällt.\nDie großen Bilder zwischendurch kannst du mit einem Tippen überspringen.',
    'Wenn du die App mittendrin schließt, merkt sie sich die Stelle. Beim nächsten Mal liest du mit „{cont}“ auf dem Titelbildschirm weiter.\nMit „{selBack}“ unten kommst du zur Auswahl zurück. Dann wird die gemerkte Stelle gelöscht.',
    'Gefundene Enden kommen in die „{zukan}“. Tippe auf ein Ende mit „{zFound}“, um es noch einmal zu lesen.\nEnden, die du noch nicht gefunden hast, zeigen einen Hinweis.\nWenn du weiterliest, öffnen sich auch Geschichten aus der Sicht anderer Figuren. Wie das geht, steht in der Auswahl.',
    'Deine Aufzeichnungen bleiben nur auf diesem Gerät und werden nirgendwohin gesendet.\nTippe ganz unten auf dem Titelbildschirm zweimal hintereinander auf „{reset}“, um alles zu löschen.\nDie Aufzeichnungen auf ein neues Handy zu übertragen, ist nicht möglich.',
    'Unter „{settings}“ (in einer Geschichte das ⚙️ unten) kannst du „{lblFs}“, „{lblBgm}“ und „{lblSe}“ ändern.\nDie Sprache wählst du mit „{btnLang}“ auf dem Titelbildschirm oder mit 🌐 unten in einer Geschichte.\nDiese Anleitung siehst du jederzeit wieder: „{settings}“, bei „{guideTitle}“ auf „{guideAgain}“ tippen.'
  ]
};

if (typeof module !== 'undefined') module.exports = { UIT_DE };
