"use strict";
/* Spanish (neutral, understood in both Spain and Latin America) UI dictionary,
   translated from the Japanese master (UIT.ja in index.html);
   key set mirrors UIT.en exactly - only the wording differs.
   Function values (zCount / newEnd / dupEnd) stay functions.
   Style: simple picture-book Spanish. Tale, viewpoint and ending names match
   the ES story files (SCENES_ES / ZK_ES in www\story_*_es.js). */

var UIT_ES = {
  title:'¡Sé el protagonista de los cuentos!',
  subtitle:'La historia cambia con cada elección',
  start:'Empezar', cont:'Continuar', zukan:'Colección de finales', settings:'⚙️ Ajustes',
  footVer:'v1.8.0',
  footOrig:'Todos los textos y las imágenes son originales.',
  footFirst:'Tu primera lectura sigue el cuento original.',
  footCreate:'Las historias con ramas y los finales son creaciones originales solo para esta app.',
  credit:'App de SOYOGI, consultas de cuidados y apoyo (atención solo en japonés)',
  privacy:'Política de privacidad',
  reset:'Borrar todos los registros y empezar de nuevo',
  resetConfirm:'¿Borrar de verdad? (Toca otra vez para borrar)',
  selTitle:'¿Qué cuento vas a leer?',
  momoName:'Momotaro, el niño del melocotón',
  momoTagFirst:'Tu primera lectura sigue el cuento original',
  momoTag:'Un cuento japonés lleno de aventura · 8 finales',
  oniName:'La historia del ogro', oniTag:'Momotaro con los ojos de un ogro · 5 finales',
  oniLock:'Termina Momotaro una vez para desbloquearla',
  kijiName:'La historia del Faisán', kijiTag:'La historia del compañero más pequeño · 2 finales',
  kijiLock:'Termina Momotaro junto con el Faisán para desbloquearla',
  akzName:'Caperucita Roja',
  akzTagFirst:'Tu primera lectura sigue el cuento original',
  akzTag:'Un cuento de Grimm lleno de emoción · 6 finales',
  wolfName:'La historia del Lobo', wolfTag:'La historia con los ojos del Lobo · 3 finales',
  wolfLock:'Termina Caperucita Roja una vez para desbloquearla',
  gmaName:'La historia de la abuela', gmaTag:'No está solo para que la salven · 2 finales',
  gmaLock:'Encuentra el final "La sabiduría de la abuela" para desbloquearla',
  kabuName:'El nabo gigante',
  kabuTagFirst:'Tu primera lectura sigue el cuento original',
  kabuTag:'Un cuento ruso de unir fuerzas · 4 finales',
  turnipName:'La historia del nabo', turnipTag:'Quien es arrancado también tiene sentimientos · 2 finales',
  turnipLock:'Termina El nabo gigante una vez para desbloquearla',
  mouseName:'La historia del ratón', mouseTag:'El más pequeño da el último empujón · 2 finales',
  mouseLock:'Encuentra un final en La historia del nabo para desbloquearla',
  uraName:'Urashima Taro',
  uraTagFirst:'Tu primera lectura sigue el cuento original',
  uraTag:'Un cuento japonés lleno de nostalgia · 5 finales',
  kameName:'La historia de la tortuga', kameTag:'El mejor asiento está en mi caparazón · 2 finales',
  kameLock:'Termina Urashima Taro una vez para desbloquearla',
  himeName:'La historia de la princesa Otohime', himeTag:'El deseo guardado en el tamatebako · 2 finales',
  himeLock:'Encuentra el final "Taro convertido en grulla" o "El tamatebako sin abrir" para desbloquearla',
  butaName:'Los tres cerditos',
  butaTagFirst:'Tu primera lectura sigue el cuento original',
  butaTag:'Un cuento inglés de soplar y resistir · 4 finales',
  pwolfName:'La historia del lobo hambriento', pwolfTag:'Hambriento y siempre el engañado · 2 finales',
  pwolfLock:'Termina Los tres cerditos una vez para desbloquearla',
  prengaName:'La historia de la casa de ladrillos', prengaTag:'Quien protege también tiene su orgullo · 2 finales',
  prengaLock:'Encuentra el final "El verdadero cuento inglés" o "Los 3 juntos desde el principio" para desbloquearla',
  hgName:'Hansel y Gretel',
  hgTagFirst:'Tu primera lectura sigue el cuento original',
  hgTag:'Un cuento de Grimm de la casa de dulces · 4 finales',
  majoName:'La historia de la bruja', majoTag:'Tantos años horneando dulces sola · 2 finales',
  majoLock:'Termina Hansel y Gretel una vez para desbloquearla',
  toriName:'La historia del pájaro blanco', toriTag:'Las migas de pan me las comí yo · 2 finales',
  toriLock:'Encuentra el final "A la otra orilla" o "El invierno del pueblo" para desbloquearla',
  kgName:'La princesa Kaguya',
  kgTagFirst:'Tu primera lectura sigue el cuento original',
  kgTag:'Un cuento japonés de la princesa que vuelve a la Luna · 4 finales',
  okinaName:'La historia del Cortador de Bambú', okinaTag:'Los días que siguieron para los dos que quedaron · 2 finales',
  okinaLock:'Termina La princesa Kaguya una vez para desbloquearla',
  tsukiName:'La historia del enviado de la Luna', tsukiTag:'Viene de un país que no conoce las lágrimas · 2 finales',
  tsukiLock:'Encuentra el final "Antes del manto de plumas" o "El elixir de la vida" para desbloquearla',
  brName:'Los músicos de Bremen',
  brTagFirst:'Tu primera lectura sigue el cuento original',
  brTag:'Un cuento de Grimm de 4 voces en coro · 4 finales',
  dorobouName:'La historia de los ladrones', dorobouTag:'El ladrón que volvió a la casa a oscuras · 2 finales',
  dorobouLock:'Termina Los músicos de Bremen una vez para desbloquearla',
  ondoriName:'La historia del gallo', ondoriTag:'La voz que iba a acabar en la sopa · 2 finales',
  ondoriLock:'Encuentra el final "En la ciudad de Bremen" o "La mañana en el bosque" para desbloquearla',
  juName:'Cómo se eligieron los 12 animales',
  juTagFirst:'Tu primera lectura sigue el cuento original',
  juTag:'Un cuento japonés de cómo los años recibieron su nombre · 4 finales',
  jnekoName:'La historia del gato', jnekoTag:'El gato que oyó mal el día · 2 finales',
  jnekoLock:'Termina Cómo se eligieron los 12 animales una vez para desbloquearla',
  jnezumiName:'La historia de la rata', jnezumiTag:'La rata que no dijo el día verdadero · 2 finales',
  jnezumiLock:'Encuentra el final "Sobre el lomo del buey" o "El saludo de cada año" para desbloquearla',
  tsName:'La grulla que devolvió el favor',
  tsTagFirst:'Tu primera lectura sigue el cuento original',
  tsTag:'Un cuento japonés de la grulla en un día de nieve · 4 finales',
  tsuruName:'La historia de la grulla', tsuruTag:'La grulla que cuenta sus plumas mientras teje · 2 finales',
  tsuruLock:'Termina "La grulla que devolvió el favor" una vez para desbloquearla',
  /* 🔴あかずきんの La historia de la abuela と まぎれない ように invierno を 入れる */
  tbaaName:'El invierno de la anciana', tbaaTag:'Le dijeron que no mirara · 2 finales',
  tbaaLock:'Encuentra el final "Ya no hace falta tejer" o "Un invierno sin mirar" para desbloquearla',
  /* 🔴"Alibaba" と つづけて 書かない(分かち書きの "Ali Baba" だけ) */
  abName:'Ali Baba y los 40 ladrones',
  abTagFirst:'Tu primera lectura sigue el cuento original',
  abTag:'Un cuento persa de la puerta de roca · 4 finales',
  moruName:'La historia de Morgiana', moruTag:'La sirvienta a la que no se le escapa nada · 2 finales',
  moruLock:'Termina Ali Baba y los 40 ladrones una vez para desbloquearla',
  /* 🔴ブレーメンの La historia de los ladrones と まぎれない ように jefe と 書く */
  kashiraName:'La historia del jefe de los ladrones',
  kashiraTag:'El jefe al que le descubrieron el secreto · 2 finales',
  kashiraLock:'Encuentra el final "Cuerdas y la guardia" o "El jefe huyó" para desbloquearla',
  kzName:'El Viento del Norte y el Sol',
  kzTagFirst:'Tu primera lectura sigue el cuento original',
  kzTag:'Una fábula de Esopo sobre quitar un abrigo · 4 finales',
  kitakazeName:'La historia del Viento del Norte', kitakazeTag:'Soplar fuerte es el trabajo del Viento del Norte · 2 finales',
  kitakazeLock:'Termina El Viento del Norte y el Sol una vez para desbloquearla',
  taiyouName:'La historia del Sol', taiyouTag:'Brillar es el trabajo del Sol · 2 finales',
  taiyouLock:'Encuentra el final "Día de lavar entre los dos" o "Un descanso a la sombra" para desbloquearla',
  prep:'Próximamente',
  titleBack:'Volver al título', selBack:'Volver a la selección', next:'Siguiente ▼', back:'Atrás',
  zTitle:'Colección de finales',
  zCount:(n,t)=>'Finales encontrados: '+n+' / '+t,
  zNote:'* Salvo el final del cuento original, todos los finales son creaciones originales solo para esta app.',
  zFound:'▶ Toca para leer de nuevo', zHint:'Pista: ', unknown:'? ? ?',
  newEnd:n=>'★ ¡Nuevo final "'+n+'" añadido a tu colección!',
  dupEnd:n=>'(El final "'+n+'" ya está en tu colección)',
  unlockChoice:'★ ¡A partir de ahora puedes elegir tu propio camino!',
  unlockNote:'(Las historias con ramas son creaciones originales solo para esta app)',
  unlockOni:'★ ¡Ya puedes leer "La historia del ogro"!',
  unlockKiji:'★ ¡Ya puedes leer "La historia del Faisán"!',
  unlockWolf:'★ ¡Ya puedes leer "La historia del Lobo"!',
  unlockGma:'★ ¡Ya puedes leer "La historia de la abuela"!',
  unlockTurnip:'★ ¡Ya puedes leer "La historia del nabo"!',
  unlockMouse:'★ ¡Ya puedes leer "La historia del ratón"!',
  unlockKame:'★ ¡Ya puedes leer "La historia de la tortuga"!',
  unlockHime:'★ ¡Ya puedes leer "La historia de la princesa Otohime"!',
  unlockPwolf:'★ ¡Ya puedes leer "La historia del lobo hambriento"!',
  unlockPrenga:'★ ¡Ya puedes leer "La historia de la casa de ladrillos"!',
  unlockMajo:'★ ¡Ya puedes leer "La historia de la bruja"!',
  unlockTori:'★ ¡Ya puedes leer "La historia del pájaro blanco"!',
  unlockOkina:'★ ¡Ya puedes leer "La historia del Cortador de Bambú"!',
  unlockTsuki:'★ ¡Ya puedes leer "La historia del enviado de la Luna"!',
  unlockDorobou:'★ ¡Ya puedes leer "La historia de los ladrones"!',
  unlockOndori:'★ ¡Ya puedes leer "La historia del gallo"!',
  unlockJneko:'★ ¡Ya puedes leer "La historia del gato"!',
  unlockJnezumi:'★ ¡Ya puedes leer "La historia de la rata"!',
  unlockTsuru:'★ ¡Ya puedes leer "La historia de la grulla"!',
  unlockTbaa:'★ ¡Ya puedes leer "El invierno de la anciana"!',
  unlockMoru:'★ ¡Ya puedes leer "La historia de Morgiana"!',
  unlockKashira:'★ ¡Ya puedes leer "La historia del jefe de los ladrones"!',
  unlockKitakaze:'★ ¡Ya puedes leer "La historia del Viento del Norte"!',
  unlockTaiyou:'★ ¡Ya puedes leer "La historia del Sol"!',
  btnZukan:'Ver la colección de finales', btnAgain:'Leer este cuento otra vez',
  btnSelect:'Volver a la selección', btnZBack:'Volver a la colección',
  setTitle:'Ajustes', lblFs:'Tamaño del texto', lblBgm:'Música', lblSe:'Efectos de sonido', lblLang:'Idioma / Language',
  fsOpts:['Pequeño','Normal','Grande'], volOpts:['Apagado','Bajo','Normal','Alto'],
  seal:['Fin']
};

if (typeof module !== 'undefined') module.exports = { UIT_ES };
