"use strict";
/* French UI dictionary, translated from the Japanese master (UIT.ja in index.html);
   key set mirrors UIT.en exactly - only the wording differs.
   Function values (zCount / newEnd / dupEnd) stay functions.
   Style: simple picture-book French. Ending names match ZK_FR in www\story_*_fr.js. */

var UIT_FR = {
  title:'Deviens le héros des contes !',
  subtitle:'L\'histoire change à chaque choix',
  start:'Commencer', cont:'Reprendre la lecture', zukan:'Collection des fins', settings:'⚙️ Réglages',
  footVer:'v1.8.0',
  footOrig:'Tous les textes et toutes les images sont originaux.',
  footFirst:'Ta première lecture suit l\'histoire d\'origine.',
  footCreate:'Les histoires à choix et les fins sont des créations originales pour cette application.',
  credit:'Application développée par SOYOGI, le point d\'écoute pour les soins et le soutien (consultations en japonais uniquement)',
  privacy:'Politique de confidentialité',
  reset:'Effacer tous les enregistrements et recommencer',
  resetConfirm:'Vraiment tout effacer ? (Appuie encore une fois pour effacer)',
  selTitle:'Quelle histoire vas-tu lire ?',
  momoName:'Momotaro, l\'enfant de la pêche',
  momoTagFirst:'Ta première lecture suit l\'histoire d\'origine',
  momoTag:'Un conte japonais plein d\'aventure · 8 fins',
  oniName:'L\'histoire de l\'ogre', oniTag:'Momotaro vu par les yeux d\'un ogre · 5 fins',
  oniLock:'Termine Momotaro une fois pour la débloquer',
  kijiName:'L\'histoire du Faisan', kijiTag:'L\'histoire du plus petit des compagnons · 2 fins',
  kijiLock:'Termine Momotaro avec le Faisan pour la débloquer',
  akzName:'Le Petit Chaperon rouge',
  akzTagFirst:'Ta première lecture suit l\'histoire d\'origine',
  akzTag:'Un conte de Grimm plein de suspense · 6 fins',
  wolfName:'L\'histoire du Loup', wolfTag:'L\'histoire vue par les yeux du loup · 3 fins',
  wolfLock:'Termine Le Petit Chaperon rouge une fois pour la débloquer',
  gmaName:'L\'histoire de la grand-mère', gmaTag:'Elle n\'est pas là seulement pour être sauvée · 2 fins',
  gmaLock:'Trouve la fin « La sagesse de grand-mère » pour la débloquer',
  kabuName:'Le gros navet',
  kabuTagFirst:'Ta première lecture suit l\'histoire d\'origine',
  kabuTag:'Un conte russe où l\'on unit ses forces · 4 fins',
  turnipName:'L\'histoire du navet', turnipTag:'Celui qu\'on tire a lui aussi des sentiments · 2 fins',
  turnipLock:'Termine Le gros navet une fois pour la débloquer',
  mouseName:'L\'histoire de la souris', mouseTag:'La plus petite donne la dernière poussée · 2 fins',
  mouseLock:'Trouve une fin dans « L\'histoire du navet » pour la débloquer',
  uraName:'Urashima Taro',
  uraTagFirst:'Ta première lecture suit l\'histoire d\'origine',
  uraTag:'Un conte japonais plein de mélancolie · 5 fins',
  kameName:'L\'histoire de la tortue', kameTag:'La meilleure place, c\'est sur ma carapace · 2 fins',
  kameLock:'Termine Urashima Taro une fois pour la débloquer',
  himeName:'L\'histoire de la princesse Otohime', himeTag:'Le souhait enfermé dans le tamatebako · 2 fins',
  himeLock:'Trouve la fin « Taro devenu grue » ou « Le tamatebako jamais ouvert » pour la débloquer',
  butaName:'Les trois petits cochons',
  butaTagFirst:'Ta première lecture suit l\'histoire d\'origine',
  butaTag:'Un conte anglais qui résiste au grand souffle · 4 fins',
  pwolfName:'L\'histoire du loup affamé', pwolfTag:'Affamé, et toujours celui qu\'on berne · 2 fins',
  pwolfLock:'Termine Les trois petits cochons une fois pour la débloquer',
  prengaName:'L\'histoire de la maison de briques', prengaTag:'Celui qui protège a lui aussi sa fierté · 2 fins',
  prengaLock:'Trouve la fin « La vraie histoire anglaise » ou « À 3 dès le début » pour la débloquer',
  hgName:'Hansel et Gretel',
  hgTagFirst:'Ta première lecture suit l\'histoire d\'origine',
  hgTag:'Un conte de Grimm avec une maison en sucreries · 4 fins',
  majoName:'L\'histoire de la sorcière', majoTag:'Toutes ces années à faire des gâteaux, seule · 2 fins',
  majoLock:'Termine Hansel et Gretel une fois pour la débloquer',
  toriName:'L\'histoire de l\'oiseau blanc', toriTag:'Les miettes de pain, c\'est moi qui les ai mangées · 2 fins',
  toriLock:'Trouve la fin « Sur l\'autre rive » ou « L\'hiver du village » pour la débloquer',
  kgName:'Princesse Kaguya',
  kgTagFirst:'Ta première lecture suit l\'histoire d\'origine',
  kgTag:'Un conte japonais de la princesse qui retourne sur la Lune · 4 fins',
  okinaName:'L\'histoire du Coupeur de bambou', okinaTag:'Les jours d\'après, pour les deux qui restent · 2 fins',
  okinaLock:'Termine Princesse Kaguya une fois pour la débloquer',
  tsukiName:'L\'histoire du messager de la Lune', tsukiTag:'Venu d\'un pays qui ne connaît pas les larmes · 2 fins',
  tsukiLock:'Trouve la fin « Avant la robe de plumes » ou « L\'élixir de vie » pour la débloquer',
  brName:'Les musiciens de Brême',
  brTagFirst:'Ta première lecture suit l\'histoire d\'origine',
  brTag:'Un conte de Grimm à 4 voix en chœur · 4 fins',
  dorobouName:'L\'histoire des brigands', dorobouTag:'Le brigand qui est retourné dans la maison sombre · 2 fins',
  dorobouLock:'Termine Les musiciens de Brême une fois pour la débloquer',
  ondoriName:'L\'histoire du coq', ondoriTag:'La voix qui devait finir en soupe · 2 fins',
  ondoriLock:'Trouve la fin « Dans la ville de Brême » ou « Le matin dans la forêt » pour la débloquer',
  juName:'Comment les 12 animaux furent choisis',
  juTagFirst:'Ta première lecture suit l\'histoire d\'origine',
  juTag:'Un conte du Japon sur le nom des années · 4 fins',
  jnekoName:'L\'histoire du chat', jnekoTag:'Le chat qui n\'a pas bien entendu le jour · 2 fins',
  jnekoLock:'Termine « Comment les 12 animaux furent choisis » une fois pour la débloquer',
  jnezumiName:'L\'histoire du rat', jnezumiTag:'Le rat qui n\'a pas dit le vrai jour · 2 fins',
  jnezumiLock:'Trouve la fin « Sur le dos du bœuf » ou « Le salut de chaque année » pour la débloquer',
  tsName:'La grue qui rendit le bienfait',
  tsTagFirst:'Ta première lecture suit l\'histoire d\'origine',
  tsTag:'Un conte du Japon, la grue d\'un jour de neige · 4 fins',
  tsuruName:'L\'histoire de la grue', tsuruTag:'La grue qui tisse en comptant ses plumes · 2 fins',
  tsuruLock:'Termine « La grue qui rendit le bienfait » une fois pour la débloquer',
  /* 🔴あかずきんの L'histoire de la grand-mère と まぎれない ように hiver を 入れる */
  tbaaName:'L\'hiver de la vieille femme', tbaaTag:'On lui avait dit de ne pas regarder · 2 fins',
  tbaaLock:'Trouve la fin « Tu n\'as plus besoin de tisser » ou « Un hiver sans regarder » pour le débloquer',
  /* 🔴"Alibaba" と つづけて 書かない(分かち書きの "Ali Baba" だけ) */
  abName:'Ali Baba et les 40 voleurs',
  abTagFirst:'Ta première lecture suit l\'histoire d\'origine',
  abTag:'Un conte persan avec une porte de pierre · 4 fins',
  moruName:'L\'histoire de Morgiana', moruTag:'La servante à qui rien n\'échappe · 2 fins',
  moruLock:'Termine Ali Baba et les 40 voleurs une fois pour la débloquer',
  /* 🔴ブレーメンの L'histoire des brigands と まぎれない ように chef des voleurs と 書く */
  kashiraName:'L\'histoire du chef des voleurs',
  kashiraTag:'Le chef des voleurs dont le secret a été découvert · 2 fins',
  kashiraLock:'Trouve la fin « Les cordes et la garde » ou « Le chef s\'est enfui » pour la débloquer',
  kzName:'Le Vent du Nord et le Soleil',
  kzTagFirst:'Ta première lecture suit l\'histoire d\'origine',
  kzTag:'Une fable d\'Ésope, le défi du manteau · 4 fins',
  kitakazeName:'L\'histoire du Vent du Nord', kitakazeTag:'Souffler fort, c\'est le travail du Vent du Nord · 2 fins',
  kitakazeLock:'Termine Le Vent du Nord et le Soleil une fois pour la débloquer',
  taiyouName:'L\'histoire du Soleil', taiyouTag:'Éclairer, c\'est le travail du Soleil · 2 fins',
  taiyouLock:'Trouve la fin « Un temps de lessive à deux » ou « Une pause à l\'ombre » pour la débloquer',
  prep:'Bientôt disponible',
  titleBack:'Retour au titre', selBack:'Retour au choix des histoires', next:'Suite ▼', back:'Retour',
  zTitle:'Collection des fins',
  zCount:(n,t)=>'Fins trouvées : '+n+' / '+t,
  zNote:'* Sauf la fin d\'origine, toutes les fins sont des créations originales pour cette application.',
  zFound:'▶ Appuie pour relire', zHint:'Indice : ', unknown:'? ? ?',
  newEnd:n=>'★ Nouvelle fin « '+n+' » ajoutée à ta collection !',
  dupEnd:n=>'(La fin « '+n+' » est déjà dans ta collection)',
  unlockChoice:'★ À partir de maintenant, tu peux choisir ton propre chemin !',
  unlockNote:'(Les histoires à choix sont des créations originales pour cette application)',
  unlockOni:'★ « L\'histoire de l\'ogre » est maintenant débloquée !',
  unlockKiji:'★ « L\'histoire du Faisan » est maintenant débloquée !',
  unlockWolf:'★ « L\'histoire du Loup » est maintenant débloquée !',
  unlockGma:'★ « L\'histoire de la grand-mère » est maintenant débloquée !',
  unlockTurnip:'★ « L\'histoire du navet » est maintenant débloquée !',
  unlockMouse:'★ « L\'histoire de la souris » est maintenant débloquée !',
  unlockKame:'★ « L\'histoire de la tortue » est maintenant débloquée !',
  unlockHime:'★ « L\'histoire de la princesse Otohime » est maintenant débloquée !',
  unlockPwolf:'★ « L\'histoire du loup affamé » est maintenant débloquée !',
  unlockPrenga:'★ « L\'histoire de la maison de briques » est maintenant débloquée !',
  unlockMajo:'★ « L\'histoire de la sorcière » est maintenant débloquée !',
  unlockTori:'★ « L\'histoire de l\'oiseau blanc » est maintenant débloquée !',
  unlockOkina:'★ « L\'histoire du Coupeur de bambou » est maintenant débloquée !',
  unlockTsuki:'★ « L\'histoire du messager de la Lune » est maintenant débloquée !',
  unlockDorobou:'★ « L\'histoire des brigands » est maintenant débloquée !',
  unlockOndori:'★ « L\'histoire du coq » est maintenant débloquée !',
  unlockJneko:'★ « L\'histoire du chat » est maintenant débloquée !',
  unlockJnezumi:'★ « L\'histoire du rat » est maintenant débloquée !',
  unlockTsuru:'★ « L\'histoire de la grue » est maintenant débloquée !',
  unlockTbaa:'★ « L\'hiver de la vieille femme » est maintenant débloqué !',
  unlockMoru:'★ « L\'histoire de Morgiana » est maintenant débloquée !',
  unlockKashira:'★ « L\'histoire du chef des voleurs » est maintenant débloquée !',
  unlockKitakaze:'★ « L\'histoire du Vent du Nord » est maintenant débloquée !',
  unlockTaiyou:'★ « L\'histoire du Soleil » est maintenant débloquée !',
  btnZukan:'Voir la collection des fins', btnAgain:'Relire cette histoire',
  btnSelect:'Retour au choix des histoires', btnZBack:'Retour à la collection',
  setTitle:'Réglages', lblFs:'Taille du texte', lblBgm:'Musique', lblSe:'Effets sonores', lblLang:'Langue / Language',
  fsOpts:['Petite','Normale','Grande'], volOpts:['Aucun','Faible','Normal','Fort'],
  seal:['Fin']
};

if (typeof module !== 'undefined') module.exports = { UIT_FR };
