"use strict";
/* Italian UI dictionary, translated from the Japanese master (UIT.ja in index.html);
   key set mirrors UIT.en exactly - only the wording differs.
   Function values (zCount / newEnd / dupEnd) stay functions.
   Style: simple picture-book Italian. Ending names match ZK_IT in www\story_*_it.js. */

var UIT_IT = {
  title:'Diventa il protagonista delle fiabe!',
  subtitle:'A ogni scelta la storia cambia',
  start:'Inizia', cont:'Continua a leggere', zukan:'Raccolta dei finali', settings:'⚙️ Impostazioni',
  footVer:'v1.8.0',
  footOrig:'Tutti i testi e i disegni sono originali.',
  footFirst:'La tua prima lettura segue la storia originale.',
  footCreate:'Le storie con le scelte e i finali sono creazioni originali solo per questa app.',
  credit:'App di SOYOGI, sportello di consulenza su cura e sostegno (consulenza solo in giapponese)',
  privacy:'Informativa sulla privacy',
  reset:'Cancella tutti i dati e ricomincia',
  resetConfirm:'Cancellare davvero? (Premi di nuovo per cancellare)',
  selTitle:'Quale storia vuoi leggere?',
  momoName:'Momotaro, il bambino della pesca',
  momoTagFirst:'La tua prima lettura segue la storia originale',
  momoTag:'Una fiaba giapponese di avventura · 8 finali',
  oniName:'La storia dell\'orco', oniTag:'Momotaro visto con gli occhi di un orco · 5 finali',
  oniLock:'Finisci Momotaro una volta per sbloccarla',
  kijiName:'La storia del Fagiano', kijiTag:'La storia del compagno più piccolo · 2 finali',
  kijiLock:'Finisci Momotaro insieme al Fagiano per sbloccarla',
  akzName:'Cappuccetto Rosso',
  akzTagFirst:'La tua prima lettura segue la storia originale',
  akzTag:'Una fiaba dei Grimm piena di suspense · 6 finali',
  wolfName:'La storia del lupo', wolfTag:'La storia vista con gli occhi del lupo · 3 finali',
  wolfLock:'Finisci Cappuccetto Rosso una volta per sbloccarla',
  gmaName:'La storia della nonna', gmaTag:'Non è lì solo per essere salvata · 2 finali',
  gmaLock:'Trova il finale "La saggezza della nonna" per sbloccarla',
  kabuName:'La rapa gigante',
  kabuTagFirst:'La tua prima lettura segue la storia originale',
  kabuTag:'Una fiaba russa sull\'unire le forze · 4 finali',
  turnipName:'La storia della rapa', turnipTag:'Anche chi viene tirato ha i suoi sentimenti · 2 finali',
  turnipLock:'Finisci La rapa gigante una volta per sbloccarla',
  mouseName:'La storia del topolino', mouseTag:'Il più piccolo dà la spinta finale · 2 finali',
  mouseLock:'Trova un finale nella Storia della rapa per sbloccarla',
  uraName:'Urashima Taro',
  uraTagFirst:'La tua prima lettura segue la storia originale',
  uraTag:'Una fiaba giapponese malinconica · 5 finali',
  kameName:'La storia della tartaruga', kameTag:'Il posto migliore è sul mio guscio · 2 finali',
  kameLock:'Finisci Urashima Taro una volta per sbloccarla',
  himeName:'La storia della principessa Otohime', himeTag:'Il desiderio chiuso nel tamatebako · 2 finali',
  himeLock:'Trova il finale "Taro diventa una gru" o "Il tamatebako mai aperto" per sbloccarla',
  butaName:'I tre porcellini',
  butaTagFirst:'La tua prima lettura segue la storia originale',
  butaTag:'Una fiaba inglese di soffi e di case che resistono · 4 finali',
  pwolfName:'La storia del lupo affamato', pwolfTag:'Affamato, e sempre quello ingannato · 2 finali',
  pwolfLock:'Finisci I tre porcellini una volta per sbloccarla',
  prengaName:'La storia della casa di mattoni', prengaTag:'Anche chi protegge ha il suo orgoglio · 2 finali',
  prengaLock:'Trova il finale "La vera storia inglese" o "Insieme fin dall\'inizio" per sbloccarla',
  hgName:'Hansel e Gretel',
  hgTagFirst:'La tua prima lettura segue la storia originale',
  hgTag:'Una fiaba dei Grimm con la casa di dolci · 4 finali',
  majoName:'La storia della strega', majoTag:'Preparare dolci da sola, per tutti quegli anni · 2 finali',
  majoLock:'Finisci Hansel e Gretel una volta per sbloccarla',
  toriName:'La storia dell\'uccello bianco', toriTag:'Le briciole di pane le ho mangiate io · 2 finali',
  toriLock:'Trova il finale "Sull\'altra riva" o "L\'inverno del villaggio" per sbloccarla',
  kgName:'Principessa Kaguya',
  kgTagFirst:'La tua prima lettura segue la storia originale',
  kgTag:'Una fiaba giapponese della principessa che torna sulla Luna · 4 finali',
  okinaName:'La storia dei due vecchi', okinaTag:'I giorni che seguirono, per i due rimasti · 2 finali',
  okinaLock:'Finisci Principessa Kaguya una volta per sbloccarla',
  tsukiName:'La storia del messaggero della Luna', tsukiTag:'Da un paese che non conosce le lacrime · 2 finali',
  tsukiLock:'Trova il finale "Prima della veste di piume" o "L\'elisir di lunga vita" per sbloccarla',
  brName:'I musicanti di Brema',
  brTagFirst:'La tua prima lettura segue la storia originale',
  brTag:'Una fiaba dei Grimm con 4 voci in coro · 4 finali',
  dorobouName:'La storia dei ladri', dorobouTag:'Il ladro che tornò nella casa buia · 2 finali',
  dorobouLock:'Finisci I musicanti di Brema una volta per sbloccarla',
  ondoriName:'La storia del gallo', ondoriTag:'La voce che doveva diventare zuppa · 2 finali',
  ondoriLock:'Trova il finale "Nella città di Brema" o "Mattino nel bosco" per sbloccarla',
  juName:'Come furono scelti i dodici animali',
  juTagFirst:'La tua prima lettura segue la storia originale',
  juTag:'Una fiaba giapponese su come gli anni ebbero i loro nomi · 4 finali',
  jnekoName:'La storia del gatto', jnekoTag:'Il gatto che non sentì il giorno dell\'annuncio · 2 finali',
  jnekoLock:'Finisci Come furono scelti i dodici animali una volta per sbloccarla',
  jnezumiName:'La storia del Topo', jnezumiTag:'Il topo che non disse il giorno vero · 2 finali',
  jnezumiLock:'Trova il finale "Sulla schiena del bue" o "Il saluto di ogni anno" per sbloccarla',
  tsName:'La gru che ricambiò la gentilezza',
  tsTagFirst:'La tua prima lettura segue la storia originale',
  tsTag:'Una fiaba giapponese della gru in un giorno di neve · 4 finali',
  tsuruName:'La storia della gru', tsuruTag:'La gru che conta le piume mentre tesse · 2 finali',
  tsuruLock:'Finisci "La gru che ricambiò la gentilezza" una volta per sbloccarla',
  /* 🔴あかずきんの La storia della nonna と まぎれない ように inverno と vecchia に する */
  tbaaName:'L\'inverno della vecchia', tbaaTag:'Le avevano detto di non guardare · 2 finali',
  tbaaLock:'Trova il finale "Non devi più tessere" o "Un inverno senza sguardi" per sbloccarla',
  /* 🔴"Alibaba" と つづけて 書かない(分かち書きの "Ali Baba" だけ) */
  abName:'Ali Baba e i 40 ladroni',
  abTagFirst:'La tua prima lettura segue la storia originale',
  abTag:'Una fiaba persiana della porta di roccia · 4 finali',
  moruName:'La storia di Morgiana', moruTag:'La serva a cui non sfugge nulla · 2 finali',
  moruLock:'Finisci Ali Baba e i 40 ladroni una volta per sbloccarla',
  /* 🔴ブレーメンの La storia dei ladri と まぎれない ように capo dei ladroni と 書く */
  kashiraName:'La storia del capo dei ladroni',
  kashiraTag:'Il capo dei ladroni a cui scoprirono il segreto · 2 finali',
  kashiraLock:'Trova il finale "Corde e guardie" o "Il capo è fuggito" per sbloccarla',
  kzName:'Il Vento del Nord e il Sole',
  kzTagFirst:'La tua prima lettura segue la storia originale',
  kzTag:'Una favola di Esopo sulla sfida per un mantello · 4 finali',
  kitakazeName:'La storia del Vento del Nord', kitakazeTag:'Soffiare forte è il lavoro del Vento del Nord · 2 finali',
  kitakazeLock:'Finisci Il Vento del Nord e il Sole una volta per sbloccarla',
  taiyouName:'La storia del Sole', taiyouTag:'Splendere è il lavoro del Sole · 2 finali',
  taiyouLock:'Trova il finale "Giornata da bucato" o "Una sosta all\'ombra" per sbloccarla',
  prep:'In preparazione',
  titleBack:'Torna al titolo', selBack:'Torna alla scelta della storia', next:'Avanti ▼', back:'Indietro',
  zTitle:'Raccolta dei finali',
  zCount:(n,t)=>'Finali trovati: '+n+' / '+t,
  zNote:'* A parte il finale originale, tutti i finali sono creazioni originali solo per questa app.',
  zFound:'▶ Tocca per rileggere', zHint:'Indizio: ', unknown:'? ? ?',
  newEnd:n=>'★ Nuovo finale "'+n+'" aggiunto alla raccolta!',
  dupEnd:n=>'(Il finale "'+n+'" è già nella tua raccolta)',
  unlockChoice:'★ D\'ora in poi puoi scegliere tu la tua strada!',
  unlockNote:'(Le storie con le scelte sono creazioni originali solo per questa app)',
  unlockOni:'★ "La storia dell\'orco" ora è sbloccata!',
  unlockKiji:'★ "La storia del Fagiano" ora è sbloccata!',
  unlockWolf:'★ "La storia del lupo" ora è sbloccata!',
  unlockGma:'★ "La storia della nonna" ora è sbloccata!',
  unlockTurnip:'★ "La storia della rapa" ora è sbloccata!',
  unlockMouse:'★ "La storia del topolino" ora è sbloccata!',
  unlockKame:'★ "La storia della tartaruga" ora è sbloccata!',
  unlockHime:'★ "La storia della principessa Otohime" ora è sbloccata!',
  unlockPwolf:'★ "La storia del lupo affamato" ora è sbloccata!',
  unlockPrenga:'★ "La storia della casa di mattoni" ora è sbloccata!',
  unlockMajo:'★ "La storia della strega" ora è sbloccata!',
  unlockTori:'★ "La storia dell\'uccello bianco" ora è sbloccata!',
  unlockOkina:'★ "La storia dei due vecchi" ora è sbloccata!',
  unlockTsuki:'★ "La storia del messaggero della Luna" ora è sbloccata!',
  unlockDorobou:'★ "La storia dei ladri" ora è sbloccata!',
  unlockOndori:'★ "La storia del gallo" ora è sbloccata!',
  unlockJneko:'★ "La storia del gatto" ora è sbloccata!',
  unlockJnezumi:'★ "La storia del Topo" ora è sbloccata!',
  unlockTsuru:'★ "La storia della gru" ora è sbloccata!',
  unlockTbaa:'★ "L\'inverno della vecchia" ora è sbloccata!',
  unlockMoru:'★ "La storia di Morgiana" ora è sbloccata!',
  unlockKashira:'★ "La storia del capo dei ladroni" ora è sbloccata!',
  unlockKitakaze:'★ "La storia del Vento del Nord" ora è sbloccata!',
  unlockTaiyou:'★ "La storia del Sole" ora è sbloccata!',
  btnZukan:'Guarda la raccolta dei finali', btnAgain:'Rileggi questa storia',
  btnSelect:'Torna alla scelta della storia', btnZBack:'Torna alla raccolta',
  setTitle:'Impostazioni', lblFs:'Dimensione del testo', lblBgm:'Musica', lblSe:'Effetti sonori', lblLang:'Lingua / Language',
  fsOpts:['Piccolo','Normale','Grande'], volOpts:['Spento','Basso','Normale','Alto'],
  seal:['Fine']
};

if (typeof module !== 'undefined') module.exports = { UIT_IT };
