"use strict";
/* Korean UI dictionary, translated from the Japanese master (UIT.ja in index.html);
   key set mirrors UIT.en exactly - only the wording differs.
   Function values (zCount / newEnd / dupEnd) stay functions.
   Style: simple picture-book Korean. Ending names match ZK_KO in www\story_*_ko.js. */

/* 결말 이름은 이야기마다 다르므로, 받침에 따라 조사를 고른다(을/를, 은/는) */
function koJosa(s, withBatchim, withoutBatchim){
  var v = String(s || '');
  var c = v.charCodeAt(v.length - 1);
  var has = (c >= 0xAC00 && c <= 0xD7A3) ? ((c - 0xAC00) % 28 !== 0) : false;
  return has ? withBatchim : withoutBatchim;
}

var UIT_KO = {
  title:'명작의 주인공이 되자!',
  subtitle:'고를 때마다 이야기가 달라집니다',
  start:'시작하기', cont:'이어서 읽기', zukan:'결말 도감', settings:'⚙️ 설정',
  footVer:'v1.8.1',
  footOrig:'글과 그림은 모두 창작입니다',
  footFirst:'첫 1회차는 원래 이야기 그대로 진행됩니다',
  footCreate:'골라서 달라지는 이야기와 결말은 이 앱만의 창작입니다',
  credit:'앱 개발: 돌봄과 지원 상담소 SOYOGI (상담은 일본어로만 가능합니다)',
  privacy:'개인정보 처리방침',
  reset:'기록을 모두 지우고 처음부터',
  resetConfirm:'정말 지울까요? (한 번 더 누르면 지웁니다)',
  selTitle:'어떤 이야기를 읽을까요?',
  momoName:'모모타로',
  momoTagFirst:'첫 1회차는 원래 이야기를 처음부터 끝까지',
  momoTag:'조마조마한 일본 옛이야기 · 결말 8가지',
  oniName:'도깨비 이야기', oniTag:'도깨비의 눈으로 본 모모타로 · 결말 5가지',
  oniLock:'모모타로를 한 번 끝까지 읽으면 열립니다',
  kijiName:'꿩 이야기', kijiTag:'가장 작은 동료의 이야기 · 결말 2가지',
  kijiLock:'모모타로를 꿩과 함께 끝내면 열립니다',
  akzName:'빨간 모자',
  akzTagFirst:'첫 1회차는 원래 이야기를 처음부터 끝까지',
  akzTag:'두근거리는 그림 형제 이야기 · 결말 6가지',
  wolfName:'늑대의 이야기', wolfTag:'늑대의 눈으로 본 이야기 · 결말 3가지',
  wolfLock:'빨간 모자를 한 번 끝까지 읽으면 열립니다',
  gmaName:'할머니의 이야기', gmaTag:'지켜지기만 하는 건 아니니까 · 결말 2가지',
  gmaLock:'결말 "할머니의 지혜"를 찾으면 열립니다',
  kabuName:'커다란 순무',
  kabuTagFirst:'첫 1회차는 원래 이야기를 처음부터 끝까지',
  kabuTag:'힘을 모으는 러시아 옛이야기 · 결말 4가지',
  turnipName:'순무의 이야기', turnipTag:'뽑히는 쪽에도 마음이 있습니다 · 결말 2가지',
  turnipLock:'커다란 순무를 한 번 끝까지 읽으면 열립니다',
  mouseName:'작은 쥐의 이야기', mouseTag:'가장 작은 마지막 한 번의 힘 · 결말 2가지',
  mouseLock:'순무의 이야기에서 결말을 하나 찾으면 열립니다',
  uraName:'우라시마 타로',
  uraTagFirst:'첫 1회차는 원래 이야기를 처음부터 끝까지',
  uraTag:'애틋한 일본 옛이야기 · 결말 5가지',
  kameName:'거북이의 이야기', kameTag:'내 등은 특등석 · 결말 2가지',
  kameLock:'우라시마 타로를 한 번 끝까지 읽으면 열립니다',
  himeName:'오토히메님의 이야기', himeTag:'다마테바코에 담은 마음 · 결말 2가지',
  himeLock:'결말 "학이 된 타로"나 "열지 않은 다마테바코"를 찾으면 열립니다',
  butaName:'아기 돼지 삼형제',
  butaTagFirst:'첫 1회차는 원래 이야기를 처음부터 끝까지',
  butaTag:'후우 후우에 지지 않는 영국 옛이야기 · 결말 4가지',
  pwolfName:'배고픈 늑대의 이야기', pwolfTag:'배가 고프고, 늘 속는 쪽 · 결말 2가지',
  pwolfLock:'아기 돼지 삼형제를 한 번 끝까지 읽으면 열립니다',
  prengaName:'벽돌집의 이야기', prengaTag:'지키는 쪽에도 자부심이 있습니다 · 결말 2가지',
  prengaLock:'결말 "영국의 진짜 이야기"나 "처음부터 3형제가 함께"를 찾으면 열립니다',
  hgName:'헨젤과 그레텔',
  hgTagFirst:'첫 1회차는 원래 이야기를 처음부터 끝까지',
  hgTag:'과자로 만든 집, 그림 형제 이야기 · 결말 4가지',
  majoName:'마녀의 이야기', majoTag:'혼자서 계속 과자를 구우며 · 결말 2가지',
  majoLock:'헨젤과 그레텔을 한 번 끝까지 읽으면 열립니다',
  toriName:'하얀 새의 이야기', toriTag:'빵부스러기를 먹은 건 바로 나 · 결말 2가지',
  toriLock:'결말 "강 건너편으로"나 "마을의 겨울"을 찾으면 열립니다',
  kgName:'가구야 공주',
  kgTagFirst:'첫 1회차는 원래 이야기를 처음부터 끝까지',
  kgTag:'달로 돌아가는 공주, 일본 옛이야기 · 결말 4가지',
  okinaName:'할아버지와 할머니의 이야기', okinaTag:'남겨진 두 사람의 그 뒤의 나날 · 결말 2가지',
  okinaLock:'가구야 공주를 한 번 끝까지 읽으면 열립니다',
  tsukiName:'달의 사자의 이야기', tsukiTag:'눈물을 모르는 나라에서 왔습니다 · 결말 2가지',
  tsukiLock:'결말 "날개옷을 입기 전에"나 "불사의 약"을 찾으면 열립니다',
  brName:'브레멘 음악대',
  brTagFirst:'첫 1회차는 원래 이야기를 처음부터 끝까지',
  brTag:'네 마리의 합창, 그림 형제 이야기 · 결말 4가지',
  dorobouName:'도둑 이야기', dorobouTag:'깜깜한 집으로 돌아간 도둑 이야기 · 결말 2가지',
  dorobouLock:'브레멘 음악대를 한 번 끝까지 읽으면 열립니다',
  ondoriName:'수탉 이야기', ondoriTag:'수프가 될 뻔했던 목소리 · 결말 2가지',
  ondoriLock:'결말 "브레멘 마을에서"나 "숲의 아침"을 찾으면 열립니다',
  juName:'십이지의 시작',
  juTagFirst:'첫 1회차는 원래 이야기를 처음부터 끝까지',
  juTag:'해의 이름이 정해진 일본 옛이야기 · 결말 4가지',
  jnekoName:'고양이의 이야기', jnekoTag:'날짜를 듣지 못한 고양이 이야기 · 결말 2가지',
  jnekoLock:'십이지의 시작을 한 번 끝까지 읽으면 열립니다',
  jnezumiName:'쥐의 이야기', jnezumiTag:'진짜 날짜를 말하지 않은 쥐 이야기 · 결말 2가지',
  jnezumiLock:'결말 "소의 등에서"나 "해마다 드리는 인사"를 찾으면 열립니다',
  tsName:'학의 보은',
  tsTagFirst:'첫 1회차는 원래 이야기를 처음부터 끝까지',
  tsTag:'눈 오는 날의 학, 일본 옛이야기 · 결말 4가지',
  tsuruName:'학의 이야기', tsuruTag:'깃털을 세어 가며 베를 짜는 학 이야기 · 결말 2가지',
  tsuruLock:'학의 보은을 한 번 끝까지 읽으면 열립니다',
  /* 🔴あかずきんの 할머니의 이야기 と まぎれない ように 겨울 を 入れる */
  tbaaName:'할머니의 겨울 이야기', tbaaTag:'보지 말라는 말을 들은 할머니 이야기 · 결말 2가지',
  tbaaLock:'결말 "이제 짜지 않아도 된다"나 "들여다보지 않은 겨울"을 찾으면 열립니다',
  abName:'알리바바와 40인의 도둑',
  abTagFirst:'첫 1회차는 원래 이야기를 처음부터 끝까지',
  abTag:'바위 문이 열리는 페르시아 옛이야기 · 결말 4가지',
  moruName:'모르지아나의 이야기', moruTag:'무엇이든 잘 알아차리는 하녀 이야기 · 결말 2가지',
  moruLock:'알리바바와 40인의 도둑을 한 번 끝까지 읽으면 열립니다',
  /* 🔴ブレーメンの 도둑 이야기 と まぎれない ように 두목 と 書く */
  kashiraName:'도둑 두목의 이야기',
  kashiraTag:'비밀을 들킨 도둑 두목 이야기 · 결말 2가지',
  kashiraLock:'결말 "밧줄과 관리"나 "두목은 달아났다"를 찾으면 열립니다',
  kzName:'북풍과 태양',
  kzTagFirst:'첫 1회차는 원래 이야기를 처음부터 끝까지',
  kzTag:'겉옷을 벗기는 겨루기, 이솝 이야기 · 결말 4가지',
  kitakazeName:'북풍의 이야기', kitakazeTag:'세게 부는 것이 일인 북풍 이야기 · 결말 2가지',
  kitakazeLock:'북풍과 태양을 한 번 끝까지 읽으면 열립니다',
  taiyouName:'태양의 이야기', taiyouTag:'비추는 것이 일인 태양 이야기 · 결말 2가지',
  taiyouLock:'결말 "둘이 만든 빨래 날"이나 "나무 그늘에서 쉬기"를 찾으면 열립니다',
  prep:'준비 중',
  titleBack:'타이틀로 돌아가기', selBack:'이야기 고르기로 돌아가기', next:'다음 ▼', back:'뒤로',
  zTitle:'결말 도감',
  zCount:(n,t)=>'찾은 결말: '+n+' / '+t,
  zNote:'※ 원래 이야기의 결말 말고는 옛이야기에는 없는, 이 앱만의 창작입니다',
  zFound:'▶ 탭하면 다시 읽기', zHint:'힌트: ', unknown:'? ? ?',
  newEnd:n=>'★ 새로운 결말 "'+n+'"'+koJosa(n,'을','를')+' 도감에 등록했습니다!',
  dupEnd:n=>'(결말 "'+n+'"'+koJosa(n,'은','는')+' 이미 등록되어 있습니다)',
  unlockChoice:'★ 다음부터는 이야기 도중에 직접 고를 수 있습니다!',
  unlockNote:'(골라서 달라지는 이야기는 이 앱만의 창작입니다)',
  unlockOni:'★ "도깨비 이야기"도 즐길 수 있게 되었습니다!',
  unlockKiji:'★ "꿩 이야기"를 즐길 수 있게 되었습니다!',
  unlockWolf:'★ "늑대의 이야기"도 즐길 수 있게 되었습니다!',
  unlockGma:'★ "할머니의 이야기"를 즐길 수 있게 되었습니다!',
  unlockTurnip:'★ "순무의 이야기"를 즐길 수 있게 되었습니다!',
  unlockMouse:'★ "작은 쥐의 이야기"를 즐길 수 있게 되었습니다!',
  unlockKame:'★ "거북이의 이야기"도 즐길 수 있게 되었습니다!',
  unlockHime:'★ "오토히메님의 이야기"를 즐길 수 있게 되었습니다!',
  unlockPwolf:'★ "배고픈 늑대의 이야기"도 즐길 수 있게 되었습니다!',
  unlockPrenga:'★ "벽돌집의 이야기"를 즐길 수 있게 되었습니다!',
  unlockMajo:'★ "마녀의 이야기"도 즐길 수 있게 되었습니다!',
  unlockTori:'★ "하얀 새의 이야기"를 즐길 수 있게 되었습니다!',
  unlockOkina:'★ "할아버지와 할머니의 이야기"도 즐길 수 있게 되었습니다!',
  unlockTsuki:'★ "달의 사자의 이야기"를 즐길 수 있게 되었습니다!',
  unlockDorobou:'★ "도둑 이야기"도 즐길 수 있게 되었습니다!',
  unlockOndori:'★ "수탉 이야기"를 즐길 수 있게 되었습니다!',
  unlockJneko:'★ "고양이의 이야기"도 즐길 수 있게 되었습니다!',
  unlockJnezumi:'★ "쥐의 이야기"를 즐길 수 있게 되었습니다!',
  unlockTsuru:'★ "학의 이야기"도 즐길 수 있게 되었습니다!',
  unlockTbaa:'★ "할머니의 겨울 이야기"를 즐길 수 있게 되었습니다!',
  unlockMoru:'★ "모르지아나의 이야기"도 즐길 수 있게 되었습니다!',
  unlockKashira:'★ "도둑 두목의 이야기"를 즐길 수 있게 되었습니다!',
  unlockKitakaze:'★ "북풍의 이야기"도 즐길 수 있게 되었습니다!',
  unlockTaiyou:'★ "태양의 이야기"를 즐길 수 있게 되었습니다!',
  btnZukan:'결말 도감 보기', btnAgain:'같은 이야기 한 번 더',
  btnSelect:'이야기 고르기로', btnZBack:'도감으로 돌아가기',
  setTitle:'설정', lblFs:'글자 크기', lblBgm:'음악', lblSe:'효과음', lblLang:'언어 / Language',
  fsOpts:['작게','보통','크게'], volOpts:['없음','작게','보통','크게'],
  seal:['끝']
};

if (typeof module !== 'undefined') module.exports = { UIT_KO };
