"use strict";
/* Dutch UI dictionary, translated from the Japanese master (UIT.ja in index.html);
   key set mirrors UIT.en exactly - only the wording differs.
   Function values (zCount / newEnd / dupEnd) stay functions.
   Style: simple picture-book Dutch. Ending names match ZK_NL in www\story_*_nl.js. */

var UIT_NL = {
  title:'Word de hoofdpersoon van de sprookjes!',
  subtitle:'Het verhaal verandert bij elke keuze',
  start:'Beginnen', cont:'Verder lezen', zukan:'Verzameling van eindes', settings:'⚙️ Instellingen',
  footVer:'v1.8.1',
  footOrig:'Alle teksten en tekeningen zijn origineel.',
  footFirst:'Je eerste keer volgt het oorspronkelijke verhaal.',
  footCreate:'De vertakkende verhalen en eindes zijn origineel, alleen voor deze app.',
  credit:'App van SOYOGI, adviespunt voor zorg en ondersteuning (advies alleen in het Japans)',
  privacy:'Privacybeleid',
  reset:'Alle gegevens wissen en opnieuw beginnen',
  resetConfirm:'Echt wissen? (Nog een keer drukken om te wissen)',
  selTitle:'Welk verhaal ga je lezen?',
  momoName:'Momotaro, de perzikjongen',
  momoTagFirst:'Je eerste keer volgt het oorspronkelijke verhaal',
  momoTag:'Een Japans verhaal vol avontuur · 8 eindes',
  oniName:'Het verhaal van de oger', oniTag:'Momotaro door de ogen van een oger · 5 eindes',
  oniLock:'Lees Momotaro één keer helemaal uit om dit vrij te spelen',
  kijiName:'Het verhaal van de fazant', kijiTag:'Het verhaal van de kleinste vriend · 2 eindes',
  kijiLock:'Speel Momotaro samen met de fazant uit om dit vrij te spelen',
  akzName:'Roodkapje',
  akzTagFirst:'Je eerste keer volgt het oorspronkelijke verhaal',
  akzTag:'Een sprookje van Grimm vol spanning · 6 eindes',
  wolfName:'Het verhaal van de wolf', wolfTag:'Het verhaal door de ogen van de wolf · 3 eindes',
  wolfLock:'Lees Roodkapje één keer helemaal uit om dit vrij te spelen',
  gmaName:'Het verhaal van grootmoeder', gmaTag:'Ze is er niet alleen om gered te worden · 2 eindes',
  gmaLock:'Vind het einde "De wijsheid van grootmoeder" om dit vrij te spelen',
  kabuName:'De grote raap',
  kabuTagFirst:'Je eerste keer volgt het oorspronkelijke verhaal',
  kabuTag:'Een Russisch verhaal over samen trekken · 4 eindes',
  turnipName:'Het verhaal van de raap', turnipTag:'Ook wie getrokken wordt, heeft gevoelens · 2 eindes',
  turnipLock:'Lees De grote raap één keer helemaal uit om dit vrij te spelen',
  mouseName:'Het verhaal van de muis', mouseTag:'De kleinste geeft het laatste zetje · 2 eindes',
  mouseLock:'Vind één einde in Het verhaal van de raap om dit vrij te spelen',
  uraName:'Urashima Taro',
  uraTagFirst:'Je eerste keer volgt het oorspronkelijke verhaal',
  uraTag:'Een Japans verhaal vol weemoed · 5 eindes',
  kameName:'Het verhaal van de schildpad', kameTag:'De beste plek is op mijn rug · 2 eindes',
  kameLock:'Lees Urashima Taro één keer helemaal uit om dit vrij te spelen',
  himeName:'Het verhaal van prinses Otohime', himeTag:'De wens, gesloten in het tamatebako · 2 eindes',
  himeLock:'Vind het einde "Taro als kraanvogel" of "Het ongeopende tamatebako" om dit vrij te spelen',
  butaName:'De drie biggetjes',
  butaTagFirst:'Je eerste keer volgt het oorspronkelijke verhaal',
  butaTag:'Een Engels verhaal over blazen en standhouden · 4 eindes',
  pwolfName:'Het verhaal van de hongerige wolf', pwolfTag:'Hongerig, en altijd degene die erin trapt · 2 eindes',
  pwolfLock:'Lees De drie biggetjes één keer helemaal uit om dit vrij te spelen',
  prengaName:'Het verhaal van het bakstenen huis', prengaTag:'Ook wie beschermt, heeft zijn trots · 2 eindes',
  prengaLock:'Vind het einde "Het echte Engelse verhaal" of "Vanaf het begin met zijn drieën" om dit vrij te spelen',
  hgName:'Hansel en Gretel',
  hgTagFirst:'Je eerste keer volgt het oorspronkelijke verhaal',
  hgTag:'Een sprookje van Grimm over een huis van snoep · 4 eindes',
  majoName:'Het verhaal van de heks', majoTag:'Al die jaren alleen snoep bakken · 2 eindes',
  majoLock:'Lees Hansel en Gretel één keer helemaal uit om dit vrij te spelen',
  toriName:'Het verhaal van de witte vogel', toriTag:'De broodkruimels heb ik opgegeten · 2 eindes',
  toriLock:'Vind het einde "Naar de overkant" of "De winter van het dorp" om dit vrij te spelen',
  kgName:'Prinses Kaguya',
  kgTagFirst:'Je eerste keer volgt het oorspronkelijke verhaal',
  kgTag:'Een Japans verhaal over de prinses die terugkeert naar de maan · 4 eindes',
  okinaName:'Het verhaal van het oude echtpaar', okinaTag:'De dagen daarna, voor de twee die achterbleven · 2 eindes',
  okinaLock:'Lees Prinses Kaguya één keer helemaal uit om dit vrij te spelen',
  tsukiName:'Het verhaal van de maanbode', tsukiTag:'Uit een land dat geen tranen kent · 2 eindes',
  tsukiLock:'Vind het einde "Voor het verenkleed" of "Het levenselixer" om dit vrij te spelen',
  brName:'De Bremer stadsmuzikanten',
  brTagFirst:'Je eerste keer volgt het oorspronkelijke verhaal',
  brTag:'Een sprookje van Grimm over 4 stemmen in koor · 4 eindes',
  dorobouName:'Het verhaal van de rovers', dorobouTag:'De rover die terugging naar het donkere huis · 2 eindes',
  dorobouLock:'Lees De Bremer stadsmuzikanten één keer helemaal uit om dit vrij te spelen',
  ondoriName:'Het verhaal van de haan', ondoriTag:'De stem die soep had moeten worden · 2 eindes',
  ondoriLock:'Vind het einde "In de stad Bremen" of "Ochtend in het bos" om dit vrij te spelen',
  juName:'Hoe de twaalf dieren werden gekozen',
  juTagFirst:'Je eerste keer volgt het oorspronkelijke verhaal',
  juTag:'Een Japans verhaal over hoe de jaren hun naam kregen · 4 eindes',
  jnekoName:'Het verhaal van de kat', jnekoTag:'De kat die de dag niet goed hoorde · 2 eindes',
  jnekoLock:'Lees Hoe de twaalf dieren werden gekozen één keer helemaal uit om dit vrij te spelen',
  jnezumiName:'Het verhaal van de rat', jnezumiTag:'De rat die de echte dag niet noemde · 2 eindes',
  jnezumiLock:'Vind het einde "Op de rug van de os" of "De groet elk jaar" om dit vrij te spelen',
  tsName:'De kraanvogel die de vriendelijkheid teruggaf',
  tsTagFirst:'Je eerste keer volgt het oorspronkelijke verhaal',
  tsTag:'Een Japans verhaal over een kraanvogel op een sneeuwdag · 4 eindes',
  tsuruName:'Het verhaal van de kraanvogel', tsuruTag:'De kraanvogel die haar veren telt terwijl ze weeft · 2 eindes',
  tsuruLock:'Lees De kraanvogel die de vriendelijkheid teruggaf één keer helemaal uit om dit vrij te spelen',
  /* 🔴あかずきんの Het verhaal van grootmoeder と まぎれない ように winter を 入れる */
  tbaaName:'De winter van de oude vrouw', tbaaTag:'Haar werd gezegd niet te kijken · 2 eindes',
  tbaaLock:'Vind het einde "Je hoeft niet meer te weven" of "Een winter zonder te kijken" om dit vrij te spelen',
  /* 🔴"Alibaba" と つづけて 書かない(分かち書きの "Ali Baba" だけ) */
  abName:'Ali Baba en de 40 rovers',
  abTagFirst:'Je eerste keer volgt het oorspronkelijke verhaal',
  abTag:'Een Perzisch verhaal over de rotsdeur · 4 eindes',
  moruName:'Het verhaal van Morgiana', moruTag:'De dienares die alles opmerkt · 2 eindes',
  moruLock:'Lees Ali Baba en de 40 rovers één keer helemaal uit om dit vrij te spelen',
  /* 🔴ブレーメンの Het verhaal van de rovers と まぎれない ように aanvoerder と 書く */
  kashiraName:'Het verhaal van de aanvoerder',
  kashiraTag:'De aanvoerder wiens geheim werd ontdekt · 2 eindes',
  kashiraLock:'Vind het einde "Touwen en de stadswacht" of "De aanvoerder vluchtte" om dit vrij te spelen',
  kzName:'De noordenwind en de zon',
  kzTagFirst:'Je eerste keer volgt het oorspronkelijke verhaal',
  kzTag:'Een fabel van Aesopus over een wedstrijd om een jas · 4 eindes',
  kitakazeName:'Het verhaal van de noordenwind', kitakazeTag:'Hard blazen is het werk van de noordenwind · 2 eindes',
  kitakazeLock:'Lees De noordenwind en de zon één keer helemaal uit om dit vrij te spelen',
  taiyouName:'Het verhaal van de zon', taiyouTag:'Schijnen is het werk van de zon · 2 eindes',
  taiyouLock:'Vind het einde "Wasweer met zijn tweeën" of "Even rusten in de schaduw" om dit vrij te spelen',
  prep:'In voorbereiding',
  titleBack:'Terug naar de titel', selBack:'Terug naar de verhaalkeuze', next:'Verder ▼', back:'Terug',
  zTitle:'Verzameling van eindes',
  zCount:(n,t)=>'Gevonden eindes: '+n+' / '+t,
  zNote:'* Behalve het oorspronkelijke einde zijn alle eindes origineel, alleen voor deze app.',
  zFound:'▶ Tik om opnieuw te lezen', zHint:'Hint: ', unknown:'? ? ?',
  newEnd:n=>'★ Nieuw einde "'+n+'" toegevoegd aan je verzameling!',
  dupEnd:n=>'(Het einde "'+n+'" staat al in je verzameling)',
  unlockChoice:'★ Vanaf nu kun je onderweg zelf kiezen!',
  unlockNote:'(De vertakkende verhalen zijn origineel, alleen voor deze app)',
  unlockOni:'★ "Het verhaal van de oger" is nu vrijgespeeld!',
  unlockKiji:'★ "Het verhaal van de fazant" is nu vrijgespeeld!',
  unlockWolf:'★ "Het verhaal van de wolf" is nu vrijgespeeld!',
  unlockGma:'★ "Het verhaal van grootmoeder" is nu vrijgespeeld!',
  unlockTurnip:'★ "Het verhaal van de raap" is nu vrijgespeeld!',
  unlockMouse:'★ "Het verhaal van de muis" is nu vrijgespeeld!',
  unlockKame:'★ "Het verhaal van de schildpad" is nu vrijgespeeld!',
  unlockHime:'★ "Het verhaal van prinses Otohime" is nu vrijgespeeld!',
  unlockPwolf:'★ "Het verhaal van de hongerige wolf" is nu vrijgespeeld!',
  unlockPrenga:'★ "Het verhaal van het bakstenen huis" is nu vrijgespeeld!',
  unlockMajo:'★ "Het verhaal van de heks" is nu vrijgespeeld!',
  unlockTori:'★ "Het verhaal van de witte vogel" is nu vrijgespeeld!',
  unlockOkina:'★ "Het verhaal van het oude echtpaar" is nu vrijgespeeld!',
  unlockTsuki:'★ "Het verhaal van de maanbode" is nu vrijgespeeld!',
  unlockDorobou:'★ "Het verhaal van de rovers" is nu vrijgespeeld!',
  unlockOndori:'★ "Het verhaal van de haan" is nu vrijgespeeld!',
  unlockJneko:'★ "Het verhaal van de kat" is nu vrijgespeeld!',
  unlockJnezumi:'★ "Het verhaal van de rat" is nu vrijgespeeld!',
  unlockTsuru:'★ "Het verhaal van de kraanvogel" is nu vrijgespeeld!',
  unlockTbaa:'★ "De winter van de oude vrouw" is nu vrijgespeeld!',
  unlockMoru:'★ "Het verhaal van Morgiana" is nu vrijgespeeld!',
  unlockKashira:'★ "Het verhaal van de aanvoerder" is nu vrijgespeeld!',
  unlockKitakaze:'★ "Het verhaal van de noordenwind" is nu vrijgespeeld!',
  unlockTaiyou:'★ "Het verhaal van de zon" is nu vrijgespeeld!',
  btnZukan:'De verzameling van eindes bekijken', btnAgain:'Dit verhaal nog een keer lezen',
  btnSelect:'Terug naar de verhaalkeuze', btnZBack:'Terug naar de verzameling',
  setTitle:'Instellingen', lblFs:'Tekstgrootte', lblBgm:'Muziek', lblSe:'Geluidseffecten', lblLang:'Taal / Language',
  fsOpts:['Klein','Normaal','Groot'], volOpts:['Uit','Zacht','Normaal','Hard'],
  seal:['Einde']
};

if (typeof module !== 'undefined') module.exports = { UIT_NL };
