"use strict";
/* Portuguese UI dictionary, translated from the Japanese master (UIT.ja in index.html);
   key set mirrors UIT.en exactly - only the wording differs.
   Function values (zCount / newEnd / dupEnd) stay functions.
   Style: simple picture-book Portuguese, neutral (understood in Brazil and Portugal).
   Ending names match ZK_PT in www\story_*_pt.js. */

var UIT_PT = {
  title:'Seja a personagem principal dos contos!',
  subtitle:'A história muda a cada escolha',
  start:'Começar', cont:'Continuar a leitura', zukan:'Coleção de finais', settings:'⚙️ Ajustes',
  footVer:'v1.8.1',
  footOrig:'Todos os textos e desenhos são originais.',
  footFirst:'A sua primeira leitura segue o conto original.',
  footCreate:'As histórias que mudam com as escolhas e os finais são criações originais deste app.',
  credit:'App da SOYOGI, ponto de consulta sobre cuidados e apoio (consultas apenas em japonês)',
  privacy:'Política de Privacidade',
  reset:'Apagar todos os dados e começar de novo',
  resetConfirm:'Apagar mesmo? (Toque outra vez para apagar)',
  selTitle:'Qual conto quer ler?',
  momoName:'Momotaro, o Menino Pêssego',
  momoTagFirst:'A sua primeira leitura segue o conto original',
  momoTag:'Um conto japonês de aventura · 8 finais',
  oniName:'A história do ogro', oniTag:'Momotaro pelos olhos de um ogro · 5 finais',
  oniLock:'Termine Momotaro uma vez para desbloquear',
  kijiName:'A história do Faisão', kijiTag:'A história do menor dos companheiros · 2 finais',
  kijiLock:'Termine Momotaro junto com o Faisão para desbloquear',
  akzName:'Chapeuzinho Vermelho',
  akzTagFirst:'A sua primeira leitura segue o conto original',
  akzTag:'Um conto dos Grimm cheio de suspense · 6 finais',
  wolfName:'A história do Lobo', wolfTag:'A história pelos olhos do Lobo · 3 finais',
  wolfLock:'Termine Chapeuzinho Vermelho uma vez para desbloquear',
  gmaName:'A história da avó', gmaTag:'Ela não está ali só para ser salva · 2 finais',
  gmaLock:'Encontre o final "A sabedoria da avó" para desbloquear',
  kabuName:'O nabo gigante',
  kabuTagFirst:'A sua primeira leitura segue o conto original',
  kabuTag:'Um conto russo sobre unir forças · 4 finais',
  turnipName:'A história do nabo', turnipTag:'Quem é puxado também tem sentimentos · 2 finais',
  turnipLock:'Termine O nabo gigante uma vez para desbloquear',
  mouseName:'A história do ratinho', mouseTag:'O menor de todos dá o último empurrão · 2 finais',
  mouseLock:'Encontre um final em A história do nabo para desbloquear',
  uraName:'Urashima Taro',
  uraTagFirst:'A sua primeira leitura segue o conto original',
  uraTag:'Um conto japonês cheio de saudade · 5 finais',
  kameName:'A história da tartaruga', kameTag:'O melhor lugar é nas minhas costas · 2 finais',
  kameLock:'Termine Urashima Taro uma vez para desbloquear',
  himeName:'A história da Princesa Otohime', himeTag:'O desejo guardado no tamatebako · 2 finais',
  himeLock:'Encontre o final "Taro, o grou" ou "O tamatebako que ficou fechado" para desbloquear',
  butaName:'Os Três Porquinhos',
  butaTagFirst:'A sua primeira leitura segue o conto original',
  butaTag:'Um conto inglês sobre não ceder ao sopro · 4 finais',
  pwolfName:'A história do lobo faminto', pwolfTag:'Faminto, e sempre o enganado · 2 finais',
  pwolfLock:'Termine Os Três Porquinhos uma vez para desbloquear',
  prengaName:'A história da casa de tijolos', prengaTag:'Quem protege também tem orgulho · 2 finais',
  prengaLock:'Encontre o final "A Verdadeira História Inglesa" ou "Os 3 Juntos desde o Começo" para desbloquear',
  hgName:'Hansel e Gretel',
  hgTagFirst:'A sua primeira leitura segue o conto original',
  hgTag:'Um conto dos Grimm sobre a casa de doces · 4 finais',
  majoName:'A história da bruxa', majoTag:'Todos esses anos assando doces sozinha · 2 finais',
  majoLock:'Termine Hansel e Gretel uma vez para desbloquear',
  toriName:'A história do pássaro branco', toriTag:'Quem comeu as migalhas fui eu · 2 finais',
  toriLock:'Encontre o final "Para a outra margem" ou "O inverno da aldeia" para desbloquear',
  kgName:'Princesa Kaguya',
  kgTagFirst:'A sua primeira leitura segue o conto original',
  kgTag:'Um conto japonês sobre a princesa que volta para a Lua · 4 finais',
  okinaName:'A história do velho casal', okinaTag:'Os dias seguintes, para os dois que ficaram · 2 finais',
  okinaLock:'Termine Princesa Kaguya uma vez para desbloquear',
  tsukiName:'A história do mensageiro da Lua', tsukiTag:'Veio de um país que não conhece lágrimas · 2 finais',
  tsukiLock:'Encontre o final "Antes do manto de plumas" ou "O elixir da vida" para desbloquear',
  brName:'Os Músicos de Bremen',
  brTagFirst:'A sua primeira leitura segue o conto original',
  brTag:'Um conto dos Grimm sobre 4 vozes em coro · 4 finais',
  dorobouName:'A história dos ladrões', dorobouTag:'O ladrão que voltou à casa escura · 2 finais',
  dorobouLock:'Termine Os Músicos de Bremen uma vez para desbloquear',
  ondoriName:'A história do galo', ondoriTag:'A voz que ia virar sopa · 2 finais',
  ondoriLock:'Encontre o final "Na cidade de Bremen" ou "Manhã na floresta" para desbloquear',
  juName:'Como os doze animais foram escolhidos',
  juTagFirst:'A sua primeira leitura segue o conto original',
  juTag:'Um conto japonês sobre como os anos ganharam nome · 4 finais',
  jnekoName:'A história do gato', jnekoTag:'O gato que ouviu o dia errado · 2 finais',
  jnekoLock:'Termine Como os doze animais foram escolhidos uma vez para desbloquear',
  jnezumiName:'A história do Rato', jnezumiTag:'O Rato que não disse o dia certo · 2 finais',
  jnezumiLock:'Encontre o final "Nas costas do boi" ou "O cumprimento de cada ano" para desbloquear',
  tsName:'O grou que retribuiu a bondade',
  tsTagFirst:'A sua primeira leitura segue o conto original',
  tsTag:'Um conto japonês sobre o grou num dia de neve · 4 finais',
  tsuruName:'A história do grou', tsuruTag:'O grou que conta as penas enquanto tece · 2 finais',
  tsuruLock:'Termine "O grou que retribuiu a bondade" uma vez para desbloquear',
  /* 🔴あかずきんの A história da avó と まぎれない ように inverno を 入れる */
  tbaaName:'O inverno da velha', tbaaTag:'Pediram a ela que não olhasse · 2 finais',
  tbaaLock:'Encontre o final "Não precisa tecer mais" ou "Um inverno sem olhar" para desbloquear',
  /* 🔴"Alibaba" と つづけて 書かない(分かち書きの "Ali Baba" だけ) */
  abName:'Ali Baba e os 40 Ladrões',
  abTagFirst:'A sua primeira leitura segue o conto original',
  abTag:'Um conto persa sobre a porta de pedra · 4 finais',
  moruName:'A história de Morgiana', moruTag:'A criada que percebe tudo · 2 finais',
  moruLock:'Termine Ali Baba e os 40 Ladrões uma vez para desbloquear',
  /* 🔴ブレーメンの A história dos ladrões と まぎれない ように chefe と 書く */
  kashiraName:'A história do chefe dos ladrões',
  kashiraTag:'O chefe dos ladrões que teve o segredo descoberto · 2 finais',
  kashiraLock:'Encontre o final "Cordas e guardas" ou "O chefe fugiu" para desbloquear',
  kzName:'O Vento Norte e o Sol',
  kzTagFirst:'A sua primeira leitura segue o conto original',
  kzTag:'Uma fábula de Esopo sobre a disputa pelo casaco · 4 finais',
  kitakazeName:'A história do Vento Norte', kitakazeTag:'Soprar forte é o trabalho do Vento Norte · 2 finais',
  kitakazeLock:'Termine O Vento Norte e o Sol uma vez para desbloquear',
  taiyouName:'A história do Sol', taiyouTag:'Brilhar é o trabalho do Sol · 2 finais',
  taiyouLock:'Encontre o final "Dia de lavar roupa" ou "Descanso na sombra" para desbloquear',
  prep:'Em preparação',
  titleBack:'Voltar ao título', selBack:'Voltar à escolha do conto', next:'Continuar ▼', back:'Voltar',
  zTitle:'Coleção de finais',
  zCount:(n,t)=>'Finais encontrados: '+n+' / '+t,
  zNote:'* Fora o final do conto original, todos os finais são criações originais deste app.',
  zFound:'▶ Toque para ler de novo', zHint:'Dica: ', unknown:'? ? ?',
  newEnd:n=>'★ Novo final "'+n+'" adicionado à sua coleção!',
  dupEnd:n=>'(O final "'+n+'" já está na sua coleção)',
  unlockChoice:'★ A partir de agora, pode escolher o seu próprio caminho!',
  unlockNote:'(As histórias que mudam com as escolhas são criações originais deste app)',
  unlockOni:'★ "A história do ogro" foi desbloqueada!',
  unlockKiji:'★ "A história do Faisão" foi desbloqueada!',
  unlockWolf:'★ "A história do Lobo" foi desbloqueada!',
  unlockGma:'★ "A história da avó" foi desbloqueada!',
  unlockTurnip:'★ "A história do nabo" foi desbloqueada!',
  unlockMouse:'★ "A história do ratinho" foi desbloqueada!',
  unlockKame:'★ "A história da tartaruga" foi desbloqueada!',
  unlockHime:'★ "A história da Princesa Otohime" foi desbloqueada!',
  unlockPwolf:'★ "A história do lobo faminto" foi desbloqueada!',
  unlockPrenga:'★ "A história da casa de tijolos" foi desbloqueada!',
  unlockMajo:'★ "A história da bruxa" foi desbloqueada!',
  unlockTori:'★ "A história do pássaro branco" foi desbloqueada!',
  unlockOkina:'★ "A história do velho casal" foi desbloqueada!',
  unlockTsuki:'★ "A história do mensageiro da Lua" foi desbloqueada!',
  unlockDorobou:'★ "A história dos ladrões" foi desbloqueada!',
  unlockOndori:'★ "A história do galo" foi desbloqueada!',
  unlockJneko:'★ "A história do gato" foi desbloqueada!',
  unlockJnezumi:'★ "A história do Rato" foi desbloqueada!',
  unlockTsuru:'★ "A história do grou" foi desbloqueada!',
  unlockTbaa:'★ "O inverno da velha" foi desbloqueado!',
  unlockMoru:'★ "A história de Morgiana" foi desbloqueada!',
  unlockKashira:'★ "A história do chefe dos ladrões" foi desbloqueada!',
  unlockKitakaze:'★ "A história do Vento Norte" foi desbloqueada!',
  unlockTaiyou:'★ "A história do Sol" foi desbloqueada!',
  btnZukan:'Ver a coleção de finais', btnAgain:'Ler este conto de novo',
  btnSelect:'Voltar à escolha do conto', btnZBack:'Voltar à coleção',
  setTitle:'Ajustes', lblFs:'Tamanho da letra', lblBgm:'Música', lblSe:'Efeitos sonoros', lblLang:'Idioma / Language',
  fsOpts:['Pequena','Normal','Grande'], volOpts:['Sem som','Baixo','Normal','Alto'],
  seal:['Fim']
};

if (typeof module !== 'undefined') module.exports = { UIT_PT };
