"use strict";
/* Swedish UI dictionary, translated from the Japanese master (UIT.ja in index.html);
   key set mirrors UIT.en exactly - only the wording differs.
   Function values (zCount / newEnd / dupEnd) stay functions.
   Style: simple picture-book Swedish. Ending names match ZK_SV in www\story_*_sv.js. */

var UIT_SV = {
  title:'Bli huvudpersonen i sagorna!',
  subtitle:'Sagan ändras varje gång du väljer',
  start:'Börja', cont:'Läs vidare', zukan:'Samling av slut', settings:'⚙️ Inställningar',
  footVer:'v1.8.1',
  footOrig:'All text och alla bilder är original.',
  footFirst:'Din första läsning följer den ursprungliga sagan.',
  footCreate:'Sagorna och sluten som ändras av dina val är original bara för den här appen.',
  credit:'App av SOYOGI, rådgivning om vård och stöd (rådgivning endast på japanska)',
  privacy:'Integritetspolicy',
  reset:'Radera alla uppgifter och börja om',
  resetConfirm:'Vill du verkligen radera? (Tryck igen för att radera)',
  selTitle:'Vilken saga vill du läsa?',
  momoName:'Momotaro, persikopojken',
  momoTagFirst:'Din första läsning följer den ursprungliga sagan',
  momoTag:'En japansk saga full av äventyr · 8 slut',
  oniName:'Trollets berättelse', oniTag:'Momotaro med trollets ögon · 5 slut',
  oniLock:'Läs klart Momotaro en gång för att låsa upp',
  kijiName:'Fasanens berättelse', kijiTag:'Sagan om den minsta vännen · 2 slut',
  kijiLock:'Klara Momotaro tillsammans med fasanen för att låsa upp',
  akzName:'Rödluvan',
  akzTagFirst:'Din första läsning följer den ursprungliga sagan',
  akzTag:'En Grimm-saga full av spänning · 6 slut',
  wolfName:'Vargens saga', wolfTag:'Sagan sedd med vargens ögon · 3 slut',
  wolfLock:'Läs klart Rödluvan en gång för att låsa upp',
  gmaName:'Mormors saga', gmaTag:'Hon finns inte bara för att bli räddad · 2 slut',
  gmaLock:'Hitta slutet ”Mormors klokhet” för att låsa upp',
  kabuName:'Den stora rovan',
  kabuTagFirst:'Din första läsning följer den ursprungliga sagan',
  kabuTag:'En rysk saga om att hjälpas åt · 4 slut',
  turnipName:'Rovans saga', turnipTag:'Den som dras upp har också känslor · 2 slut',
  turnipLock:'Läs klart Den stora rovan en gång för att låsa upp',
  mouseName:'Musens saga', mouseTag:'Den minsta ger den sista knuffen · 2 slut',
  mouseLock:'Hitta ett slut i Rovans saga för att låsa upp',
  uraName:'Urashima Taro',
  uraTagFirst:'Din första läsning följer den ursprungliga sagan',
  uraTag:'En japansk saga full av vemod · 5 slut',
  kameName:'Sköldpaddans saga', kameTag:'Bästa platsen är på min rygg · 2 slut',
  kameLock:'Läs klart Urashima Taro en gång för att låsa upp',
  himeName:'Prinsessan Otohimes saga', himeTag:'Önskan som lades i tamatebako · 2 slut',
  himeLock:'Hitta slutet ”Taro som trana” eller ”Det oöppnade tamatebako” för att låsa upp',
  butaName:'De tre små grisarna',
  butaTagFirst:'Din första läsning följer den ursprungliga sagan',
  butaTag:'En engelsk saga om att stå emot pustandet · 4 slut',
  pwolfName:'Den hungriga vargens saga', pwolfTag:'Hungrig, och alltid den som luras · 2 slut',
  pwolfLock:'Läs klart De tre små grisarna en gång för att låsa upp',
  prengaName:'Tegelhusets saga', prengaTag:'Den som skyddar har också sin stolthet · 2 slut',
  prengaLock:'Hitta slutet ”Den äkta engelska sagan” eller ”Alla 3 från början” för att låsa upp',
  hgName:'Hansel och Gretel',
  hgTagFirst:'Din första läsning följer den ursprungliga sagan',
  hgTag:'En Grimm-saga om huset av sötsaker · 4 slut',
  majoName:'Häxans saga', majoTag:'Att baka sötsaker ensam i alla dessa år · 2 slut',
  majoLock:'Läs klart Hansel och Gretel en gång för att låsa upp',
  toriName:'Den vita fågelns saga', toriTag:'Det var jag som åt brödsmulorna · 2 slut',
  toriLock:'Hitta slutet ”Till andra stranden” eller ”Byns vinter” för att låsa upp',
  kgName:'Prinsessan Kaguya',
  kgTagFirst:'Din första läsning följer den ursprungliga sagan',
  kgTag:'En japansk saga om prinsessan som vänder tillbaka till månen · 4 slut',
  okinaName:'Sagan om det gamla paret', okinaTag:'Dagarna efteråt, för de två som blev kvar · 2 slut',
  okinaLock:'Läs klart Prinsessan Kaguya en gång för att låsa upp',
  tsukiName:'Sagan om månens sändebud', tsukiTag:'Från ett land som inte känner tårar · 2 slut',
  tsukiLock:'Hitta slutet ”Före fjäderdräkten” eller ”Livselixiret” för att låsa upp',
  brName:'Bremens stadsmusikanter',
  brTagFirst:'Din första läsning följer den ursprungliga sagan',
  brTag:'En Grimm-saga om 4 röster i kör · 4 slut',
  dorobouName:'Rövarnas berättelse', dorobouTag:'Rövaren som gick tillbaka till det mörka huset · 2 slut',
  dorobouLock:'Läs klart Bremens stadsmusikanter en gång för att låsa upp',
  ondoriName:'Tuppens berättelse', ondoriTag:'Rösten som skulle ha blivit soppa · 2 slut',
  ondoriLock:'Hitta slutet ”I staden Bremen” eller ”Morgon i skogen” för att låsa upp',
  juName:'Hur de tolv djuren valdes',
  juTagFirst:'Din första läsning följer den ursprungliga sagan',
  juTag:'En japansk saga om hur åren fick sina namn · 4 slut',
  jnekoName:'Sagan om katten', jnekoTag:'Katten som hörde fel om dagen · 2 slut',
  jnekoLock:'Läs klart Hur de tolv djuren valdes en gång för att låsa upp',
  jnezumiName:'Sagan om råttan', jnezumiTag:'Råttan som inte sa den rätta dagen · 2 slut',
  jnezumiLock:'Hitta slutet ”På oxens rygg” eller ”Hälsningen varje år” för att låsa upp',
  tsName:'Tranan som gav tillbaka för vänligheten',
  tsTagFirst:'Din första läsning följer den ursprungliga sagan',
  tsTag:'En japansk saga om tranan en snöig dag · 4 slut',
  tsuruName:'Tranans saga', tsuruTag:'Tranan som räknar fjädrarna medan hon väver · 2 slut',
  tsuruLock:'Läs klart ”Tranan som gav tillbaka för vänligheten” en gång för att låsa upp',
  /* 🔴あかずきんの Mormors saga と まぎれない ように vinter を 入れる */
  tbaaName:'Den gamla kvinnans vinter', tbaaTag:'Hon blev ombedd att inte titta · 2 slut',
  tbaaLock:'Hitta slutet ”Du behöver inte väva mer” eller ”En vinter utan blick” för att låsa upp',
  /* 🔴"Alibaba" と つづけて 書かない(分かち書きの "Ali Baba" だけ) */
  abName:'Ali Baba och de 40 rövarna',
  abTagFirst:'Din första läsning följer den ursprungliga sagan',
  abTag:'En persisk saga om dörren i klippan · 4 slut',
  moruName:'Morgianas saga', moruTag:'Tjänarinnan som lägger märke till allt · 2 slut',
  moruLock:'Läs klart Ali Baba och de 40 rövarna en gång för att låsa upp',
  /* 🔴ブレーメンの Rövarnas berättelse と まぎれない ように Rövarhövdingens と 書く */
  kashiraName:'Rövarhövdingens saga',
  kashiraTag:'Hövdingen vars hemlighet blev upptäckt · 2 slut',
  kashiraLock:'Hitta slutet ”Rep och stadsvakten” eller ”Hövdingen flydde” för att låsa upp',
  kzName:'Nordanvinden och solen',
  kzTagFirst:'Din första läsning följer den ursprungliga sagan',
  kzTag:'En fabel av Aesopos om tävlingen om en kappa · 4 slut',
  kitakazeName:'Sagan om nordanvinden', kitakazeTag:'Att blåsa hårt är nordanvindens arbete · 2 slut',
  kitakazeLock:'Läs klart Nordanvinden och solen en gång för att låsa upp',
  taiyouName:'Sagan om solen', taiyouTag:'Att lysa är solens arbete · 2 slut',
  taiyouLock:'Hitta slutet ”Tvättväder tillsammans” eller ”En vila i skuggan” för att låsa upp',
  prep:'Kommer snart',
  titleBack:'Tillbaka till titeln', selBack:'Tillbaka till sagovalet', next:'Vidare ▼', back:'Tillbaka',
  zTitle:'Samling av slut',
  zCount:(n,t)=>'Hittade slut: '+n+' / '+t,
  zNote:'* Utom det ursprungliga slutet är alla slut original bara för den här appen.',
  zFound:'▶ Tryck för att läsa igen', zHint:'Ledtråd: ', unknown:'? ? ?',
  newEnd:n=>'★ Nytt slut ”'+n+'” tillagt i din samling!',
  dupEnd:n=>'(Slutet ”'+n+'” finns redan i din samling)',
  unlockChoice:'★ Från och med nu kan du välja din egen väg!',
  unlockNote:'(Sagorna som ändras av dina val är original bara för den här appen)',
  unlockOni:'★ ”Trollets berättelse” är nu upplåst!',
  unlockKiji:'★ ”Fasanens berättelse” är nu upplåst!',
  unlockWolf:'★ ”Vargens saga” är nu upplåst!',
  unlockGma:'★ ”Mormors saga” är nu upplåst!',
  unlockTurnip:'★ ”Rovans saga” är nu upplåst!',
  unlockMouse:'★ ”Musens saga” är nu upplåst!',
  unlockKame:'★ ”Sköldpaddans saga” är nu upplåst!',
  unlockHime:'★ ”Prinsessan Otohimes saga” är nu upplåst!',
  unlockPwolf:'★ ”Den hungriga vargens saga” är nu upplåst!',
  unlockPrenga:'★ ”Tegelhusets saga” är nu upplåst!',
  unlockMajo:'★ ”Häxans saga” är nu upplåst!',
  unlockTori:'★ ”Den vita fågelns saga” är nu upplåst!',
  unlockOkina:'★ ”Sagan om det gamla paret” är nu upplåst!',
  unlockTsuki:'★ ”Sagan om månens sändebud” är nu upplåst!',
  unlockDorobou:'★ ”Rövarnas berättelse” är nu upplåst!',
  unlockOndori:'★ ”Tuppens berättelse” är nu upplåst!',
  unlockJneko:'★ ”Sagan om katten” är nu upplåst!',
  unlockJnezumi:'★ ”Sagan om råttan” är nu upplåst!',
  unlockTsuru:'★ ”Tranans saga” är nu upplåst!',
  unlockTbaa:'★ ”Den gamla kvinnans vinter” är nu upplåst!',
  unlockMoru:'★ ”Morgianas saga” är nu upplåst!',
  unlockKashira:'★ ”Rövarhövdingens saga” är nu upplåst!',
  unlockKitakaze:'★ ”Sagan om nordanvinden” är nu upplåst!',
  unlockTaiyou:'★ ”Sagan om solen” är nu upplåst!',
  btnZukan:'Se samlingen av slut', btnAgain:'Läs samma saga en gång till',
  btnSelect:'Tillbaka till sagovalet', btnZBack:'Tillbaka till samlingen',
  setTitle:'Inställningar', lblFs:'Textstorlek', lblBgm:'Musik', lblSe:'Ljudeffekter', lblLang:'Språk / Language',
  fsOpts:['Liten','Normal','Stor'], volOpts:['Av','Låg','Normal','Hög'],
  seal:['Slut']
};

if (typeof module !== 'undefined') module.exports = { UIT_SV };
