"use strict";
/* Simplified Chinese UI dictionary, translated from the Japanese master (UIT.ja in index.html);
   key set mirrors UIT.en exactly - only the wording differs.
   Function values (zCount / newEnd / dupEnd) stay functions.
   Style: simple picture-book Chinese. Ending names match ZK_ZH in www\story_*_zh.js. */

var UIT_ZH = {
  title:'来当名作的主人公吧！',
  subtitle:'每选择一次，故事就会改变',
  start:'开始', cont:'接着读', zukan:'结局图鉴', settings:'⚙️ 设置',
  footVer:'v1.8.0',
  footOrig:'文字和图画全都是原创的。',
  footFirst:'第一次游玩时，会照着原本的故事往下走。',
  footCreate:'选择后改变的故事和结局，是这个应用独有的原创内容。',
  credit:'应用开发：护理与支援咨询处“SOYOGI”（咨询仅限日语）',
  privacy:'隐私政策',
  reset:'删除所有记录，从头开始',
  resetConfirm:'真的要删除吗？（再按一次就删除）',
  selTitle:'要读哪个故事呢？',
  momoName:'桃太郎',
  momoTagFirst:'第一次游玩时，从头到尾读原本的故事',
  momoTag:'充满冒险的日本故事 · 8种结局',
  oniName:'鬼的故事', oniTag:'从鬼的眼睛看桃太郎 · 5种结局',
  oniLock:'把《桃太郎》读完一次就能玩',
  kijiName:'雉鸡的故事', kijiTag:'最小的同伴的故事 · 2种结局',
  kijiLock:'和雉鸡一起通关《桃太郎》就能玩',
  akzName:'小红帽',
  akzTagFirst:'第一次游玩时，从头到尾读原本的故事',
  akzTag:'扣人心弦的格林故事 · 6种结局',
  wolfName:'狼的故事', wolfTag:'从狼的眼睛看到的故事 · 3种结局',
  wolfLock:'把《小红帽》读完一次就能玩',
  gmaName:'奶奶的故事', gmaTag:'她不是只等着被保护的人 · 2种结局',
  gmaLock:'找到结局“奶奶的智慧”就能玩',
  kabuName:'大萝卜',
  kabuTagFirst:'第一次游玩时，从头到尾读原本的故事',
  kabuTag:'齐心协力的俄罗斯故事 · 4种结局',
  turnipName:'萝卜的故事', turnipTag:'被拔的一方也有心情 · 2种结局',
  turnipLock:'把《大萝卜》读完一次就能玩',
  mouseName:'小老鼠的故事', mouseTag:'最小的那个，最后一推 · 2种结局',
  mouseLock:'在《萝卜的故事》里找到1个结局就能玩',
  uraName:'浦岛太郎',
  uraTagFirst:'第一次游玩时，从头到尾读原本的故事',
  uraTag:'带着淡淡惆怅的日本故事 · 5种结局',
  kameName:'海龟的故事', kameTag:'我的背上是最好的座位 · 2种结局',
  kameLock:'把《浦岛太郎》读完一次就能玩',
  himeName:'乙姬的故事', himeTag:'装进玉手箱里的心意 · 2种结局',
  himeLock:'找到结局“变成鹤的太郎”或“没有打开的玉手箱”就能玩',
  butaName:'三只小猪',
  butaTagFirst:'第一次游玩时，从头到尾读原本的故事',
  butaTag:'不怕呼呼吹的英国故事 · 4种结局',
  pwolfName:'饿狼的故事', pwolfTag:'肚子饿，还总是被骗的一方 · 2种结局',
  pwolfLock:'把《三只小猪》读完一次就能玩',
  prengaName:'砖房子的故事', prengaTag:'守护的一方也有骄傲 · 2种结局',
  prengaLock:'找到结局“英国真正的故事”或“一开始就3只一起”就能玩',
  hgName:'汉赛尔与格蕾特',
  hgTagFirst:'第一次游玩时，从头到尾读原本的故事',
  hgTag:'关于点心屋子的格林故事 · 4种结局',
  majoName:'女巫的故事', majoTag:'一个人一直做着点心 · 2种结局',
  majoLock:'把《汉赛尔与格蕾特》读完一次就能玩',
  toriName:'白鸟的故事', toriTag:'吃掉面包屑的，是我 · 2种结局',
  toriLock:'找到结局“到河的对岸去”或“村子的冬天”就能玩',
  kgName:'辉夜姬',
  kgTagFirst:'第一次游玩时，从头到尾读原本的故事',
  kgTag:'公主回月亮去的日本故事 · 4种结局',
  okinaName:'老爷爷和老奶奶的故事', okinaTag:'留下来的两个人，之后的日子 · 2种结局',
  okinaLock:'把《辉夜姬》读完一次就能玩',
  tsukiName:'月亮使者的故事', tsukiTag:'来自不知道眼泪的国度 · 2种结局',
  tsukiLock:'找到结局“穿羽衣之前”或“不死药”就能玩',
  brName:'不来梅的音乐家',
  brTagFirst:'第一次游玩时，从头到尾读原本的故事',
  brTag:'4只动物合唱的格林故事 · 4种结局',
  dorobouName:'强盗的故事', dorobouTag:'回到漆黑房子里的强盗的故事 · 2种结局',
  dorobouLock:'把《不来梅的音乐家》读完一次就能玩',
  ondoriName:'公鸡的故事', ondoriTag:'本该变成汤的那个声音 · 2种结局',
  ondoriLock:'找到结局“在不来梅城里”或“林子里的早晨”就能玩',
  juName:'十二生肖的由来',
  juTagFirst:'第一次游玩时，从头到尾读原本的故事',
  juTag:'关于年的名字的日本故事 · 4种结局',
  jnekoName:'猫的故事', jnekoTag:'没听清日子的猫的故事 · 2种结局',
  jnekoLock:'把《十二生肖的由来》读完一次就能玩',
  jnezumiName:'老鼠的故事', jnezumiTag:'没有说出真日子的老鼠的故事 · 2种结局',
  jnezumiLock:'找到结局“在牛背上”或“每年的问候”就能玩',
  tsName:'仙鹤报恩',
  tsTagFirst:'第一次游玩时，从头到尾读原本的故事',
  tsTag:'雪天的鹤的日本故事 · 4种结局',
  tsuruName:'鹤的故事', tsuruTag:'一边数羽毛一边织布的鹤的故事 · 2种结局',
  tsuruLock:'把《仙鹤报恩》读完一次就能玩',
  /* 🔴あかずきんの 奶奶的故事 と まぎれない ように 老奶奶 と 冬天 を 入れる */
  tbaaName:'老奶奶的冬天', tbaaTag:'被叮嘱不要看的老奶奶的故事 · 2种结局',
  tbaaLock:'找到结局“不用再织了”或“没有偷看的冬天”就能玩',
  /* 🔴"Alibaba" と つづけて 書かない(中国語は 阿里巴巴 で よい) */
  abName:'阿里巴巴和40个强盗',
  abTagFirst:'第一次游玩时，从头到尾读原本的故事',
  abTag:'关于岩石门的波斯故事 · 4种结局',
  moruName:'摩尔吉娜的故事', moruTag:'什么都注意得到的女仆的故事 · 2种结局',
  moruLock:'把《阿里巴巴和40个强盗》读完一次就能玩',
  /* 🔴ブレーメンの 强盗的故事 と まぎれない ように 强盗首领 と 書く */
  kashiraName:'强盗首领的故事',
  kashiraTag:'秘密被人知道的强盗首领的故事 · 2种结局',
  kashiraLock:'找到结局“绳子和官差”或“首领逃走了”就能玩',
  kzName:'北风和太阳',
  kzTagFirst:'第一次游玩时，从头到尾读原本的故事',
  kzTag:'比谁能脱下外衣的伊索故事 · 4种结局',
  kitakazeName:'北风的故事', kitakazeTag:'用力吹是北风的工作 · 2种结局',
  kitakazeLock:'把《北风和太阳》读完一次就能玩',
  taiyouName:'太阳的故事', taiyouTag:'照耀是太阳的工作 · 2种结局',
  taiyouLock:'找到结局“两个人的晒衣天”或“在树荫里歇一歇”就能玩',
  prep:'准备中',
  titleBack:'回到标题', selBack:'回到故事选择', next:'继续 ▼', back:'返回',
  zTitle:'结局图鉴',
  zCount:(n,t)=>'找到的结局：'+n+' / '+t,
  zNote:'※除了原本故事的结局以外，其他结局都是民间故事里没有的、这个应用独有的原创内容',
  zFound:'▶ 点一下重新读', zHint:'提示：', unknown:'？？？',
  newEnd:n=>'★把新的结局“'+n+'”登记到图鉴里了！',
  dupEnd:n=>'（结局“'+n+'”已经登记过了）',
  unlockChoice:'★从下一次开始，你可以在故事中间自己选择了！',
  unlockNote:'（选择后改变的故事，是这个应用独有的原创内容）',
  unlockOni:'★《鬼的故事》也能玩了！',
  unlockKiji:'★《雉鸡的故事》能玩了！',
  unlockWolf:'★《狼的故事》也能玩了！',
  unlockGma:'★《奶奶的故事》能玩了！',
  unlockTurnip:'★《萝卜的故事》能玩了！',
  unlockMouse:'★《小老鼠的故事》能玩了！',
  unlockKame:'★《海龟的故事》也能玩了！',
  unlockHime:'★《乙姬的故事》能玩了！',
  unlockPwolf:'★《饿狼的故事》也能玩了！',
  unlockPrenga:'★《砖房子的故事》能玩了！',
  unlockMajo:'★《女巫的故事》也能玩了！',
  unlockTori:'★《白鸟的故事》能玩了！',
  unlockOkina:'★《老爷爷和老奶奶的故事》也能玩了！',
  unlockTsuki:'★《月亮使者的故事》能玩了！',
  unlockDorobou:'★《强盗的故事》也能玩了！',
  unlockOndori:'★《公鸡的故事》能玩了！',
  unlockJneko:'★《猫的故事》也能玩了！',
  unlockJnezumi:'★《老鼠的故事》能玩了！',
  unlockTsuru:'★《鹤的故事》也能玩了！',
  unlockTbaa:'★《老奶奶的冬天》能玩了！',
  unlockMoru:'★《摩尔吉娜的故事》也能玩了！',
  unlockKashira:'★《强盗首领的故事》能玩了！',
  unlockKitakaze:'★《北风的故事》也能玩了！',
  unlockTaiyou:'★《太阳的故事》能玩了！',
  btnZukan:'看结局图鉴', btnAgain:'再读一次同一个故事',
  btnSelect:'回到故事选择', btnZBack:'回到图鉴',
  setTitle:'设置', lblFs:'文字大小', lblBgm:'音乐', lblSe:'音效', lblLang:'语言 / Language',
  fsOpts:['小','标准','大'], volOpts:['关闭','小声','标准','大声'],
  seal:['完']
};

if (typeof module !== 'undefined') module.exports = { UIT_ZH };
